// Lista ampla e genérica de profissões comuns no Brasil, usada nos campos
// de qualificação de locador/locatário/fiador. "Outra" libera texto livre.
export const PROFISSOES: string[] = [
  "Administrador(a)",
  "Advogado(a)",
  "Agricultor(a)",
  "Analista de Sistemas",
  "Analista Financeiro(a)",
  "Arquiteto(a)",
  "Assistente Administrativo(a)",
  "Assistente Social",
  "Ator/Atriz",
  "Atendente",
  "Auditor(a)",
  "Auxiliar Administrativo(a)",
  "Autônomo(a)",
  "Bancário(a)",
  "Bibliotecário(a)",
  "Biólogo(a)",
  "Bombeiro(a)",
  "Cabeleireiro(a)",
  "Caminhoneiro(a)",
  "Chef de Cozinha",
  "Cientista",
  "Contador(a)",
  "Corretor(a) de Imóveis",
  "Corretor(a) de Seguros",
  "Costureiro(a)",
  "Cozinheiro(a)",
  "Dentista",
  "Designer",
  "Desenvolvedor(a) de Software",
  "Diplomata",
  "Diretor(a)",
  "Economista",
  "Editor(a)",
  "Eletricista",
  "Empresário(a)",
  "Enfermeiro(a)",
  "Engenheiro(a) Agrônomo(a)",
  "Engenheiro(a) Civil",
  "Engenheiro(a) de Produção",
  "Engenheiro(a) Elétrico(a)",
  "Engenheiro(a) Mecânico(a)",
  "Engenheiro(a) Químico(a)",
  "Escrivão/Escrivã",
  "Escritor(a)",
  "Estagiário(a)",
  "Estatístico(a)",
  "Estudante",
  "Farmacêutico(a)",
  "Fisioterapeuta",
  "Fonoaudiólogo(a)",
  "Fotógrafo(a)",
  "Funcionário(a) Público(a)",
  "Geólogo(a)",
  "Gerente Administrativo(a)",
  "Gerente Comercial",
  "Gerente de Projetos",
  "Gerente Financeiro(a)",
  "Gestor(a) de RH",
  "Historiador(a)",
  "Jardineiro(a)",
  "Jornalista",
  "Juiz(íza)",
  "Marceneiro(a)",
  "Marinheiro(a)",
  "Mecânico(a)",
  "Médico(a)",
  "Médico(a) Veterinário(a)",
  "Militar",
  "Motoboy",
  "Motorista",
  "Músico(a)",
  "Nutricionista",
  "Odontólogo(a)",
  "Operador(a) de Caixa",
  "Operador(a) de Máquinas",
  "Padeiro(a)",
  "Pastor(a)/Pároco",
  "Pedagogo(a)",
  "Pedreiro(a)",
  "Pescador(a)",
  "Pintor(a)",
  "Piloto(a)",
  "Policial",
  "Produtor(a) Rural",
  "Professor(a)",
  "Programador(a)",
  "Promotor(a) de Justiça",
  "Psicólogo(a)",
  "Publicitário(a)",
  "Química/Químico",
  "Recepcionista",
  "Representante Comercial",
  "Securitário(a)",
  "Serralheiro(a)",
  "Servidor(a) Público(a)",
  "Sociólogo(a)",
  "Soldador(a)",
  "Supervisor(a)",
  "Taxista",
  "Técnico(a) de Enfermagem",
  "Técnico(a) de Informática",
  "Técnico(a) em Segurança do Trabalho",
  "Terapeuta Ocupacional",
  "Tradutor(a)/Intérprete",
  "Vendedor(a)",
  "Vigilante",
  "Zootecnista",
  "Aposentado(a)",
  "Do Lar",
  "Outra",
];
