-- Marca observação fixa pras imobiliárias da Tokio cuja fatura vem da
-- plataforma terceirizada SegImob (coluna "SEG IMOB" da planilha).

with nomes(nome_planilha) as (
  values
    ('PROMOVEL IMOBILIÁRIA LTDA'),
    ('BERGE'),
    ('DAHER'),
    ('RIO CAPITAL'),
    ('PROCED LOPES'),
    ('ACERVO CARIOCA'),
    ('ACESSE IMÓVEL RJ'),
    ('ADILSON BRAZ'),
    ('ADJUVE'),
    ('André gomes dos santos'),
    ('ALBERTO SOARES'),
    ('ALEXANDRE CARNEIRO'),
    ('ALEXANDRE DUHZ'),
    ('ANA CARLA ROSSI REZENDE'),
    ('BACELLAR'),
    ('BALCARCE'),
    ('BASE'),
    ('BCM'),
    ('BROTHERHOOD'),
    ('BS MACHADO'),
    ('CARLOS ADOLFO'),
    ('CASA CAPRI'),
    ('CENTRO JURIDICO'),
    ('CLAUDIA CARVALHO'),
    ('CRISTIANO ALVES'),
    ('CHEZ BRASIL'),
    ('DOMENICI'),
    ('DCS'),
    ('EXCLUSIVA'),
    ('ENJOY'),
    ('FLAVIO BRAGA MONTEIRO'),
    ('FR COSTA'),
    ('GAUCHO IMOVEIS'),
    ('GRACE GONCALVES'),
    ('HUMBERTO CANALE'),
    ('HÉLIO HIBAS (HC CONSULTORIA)'),
    ('IMOBARRA (VITAL DIAS)'),
    ('IMOVEL LIVRE'),
    ('IMOVELUM PLATAFORMA IMOBILIARIA LTDA'),
    ('I9 INOVE'),
    ('JOAO MARCO BESSA'),
    ('JOAO MARTINS'),
    ('JSJ'),
    ('VERITAS IMOVEIS SOLUÇÕES'),
    ('LAGORIO'),
    ('LIBERTY ADM (722805)'),
    ('LIVE IMOVEIS'),
    ('LÍDER RIO'),
    ('LOURENCO'),
    ('LUIS ROMEIRO'),
    ('LUIZ FLAVIO'),
    ('M V R'),
    ('MAPA'),
    ('MARREIROS IMOVEIS'),
    ('MATERDRADE'),
    ('MAX BROKERS'),
    ('METHODUS'),
    ('MONTE ALEGRE EMPREENDIMENTOS'),
    ('MONTE ALEGRE GESTÃO'),
    ('MONTENEGRO'),
    ('MORAES E VECCHI'),
    ('NELIO GOMES'),
    ('OBJETIVA'),
    ('OKRE'),
    ('PAULO SAMPAIO'),
    ('PINTAS IMOVEIS'),
    ('R N P FORMOSO CORRETAGEM'),
    ('SPECIAL RESIDENCE'),
    ('R&SA GESTÃO'),
    ('RCJ (ROGERIO CASSIANO)'),
    ('RDJ'),
    ('REAL UP'),
    ('RHIAN AZEREDO'),
    ('RJ VILLELA'),
    ('RODRIGO ARRUDA'),
    ('R SOARES'),
    ('SCASTTRO IMOVEIS'),
    ('SELLING'),
    ('SELMA MARIA CARDOSO'),
    ('SM ADM'),
    ('SPIN'),
    ('SUA CASA DIGITAL'),
    ('TAGS IMOVEIS'),
    ('TRATTO IMOVEIS'),
    ('TRAVASSOS'),
    ('SERRA REAL'),
    ('TWP'),
    ('VÂNIA AMARAL'),
    ('VENDABLE'),
    ('VIVIAN MANSUR'),
    ('MTT 100'),
    ('MTT 300'),
    ('MTT 500'),
    ('MTT 600'),
    ('ADAK'),
    ('EXPAN'),
    ('PAULA ADRIANA'),
    ('RAFAEL PENNA'),
    ('VALVERDE E FERNANDES'),
    ('BSJ'),
    ('ACVM'),
    ('SILVÉRIO IMÓVEIS'),
    ('ANDREIA BAFFA'),
    ('IMOPRET'),
    ('LUMAR'),
    ('LIBERTY ADM (614835)'),
    ('WALKER')
)
update faturas_esperadas fe
set observacao = coalesce(nullif(fe.observacao, ''), 'Buscar fatura na plataforma SegImob (terceirizada)')
from nomes n
left join imobiliarias_conhecidas ic on upper(trim(ic.nome)) = upper(trim(n.nome_planilha))
left join imobiliarias i on i.cnpj = ic.cnpj
where fe.seguradora = 'TOKIO'
  and (fe.nome_provisorio = n.nome_planilha or fe.imobiliaria_id = i.id);
