-- Preenche dia de vencimento e CNPJ da O2 (Porto Fiança/RE/Too) a partir
-- da planilha de controle. Gerado automaticamente — revisar antes de rodar.

with dados(nome_planilha, seguradora, dia_vencimento, cnpj_o2) as (
  values
    ('PROMOVEL IMOBILIÁRIA LTDA', 'TOKIO', 8, null),
    ('BERGE', 'TOKIO', 9, null),
    ('DAHER', 'TOKIO', 9, null),
    ('RIO CAPITAL', 'TOKIO', 9, null),
    ('PROCED LOPES', 'TOKIO', 10, null),
    ('ACERVO CARIOCA', 'TOKIO', 15, null),
    ('ACESSE IMÓVEL RJ', 'TOKIO', 15, null),
    ('ADILSON BRAZ', 'TOKIO', 15, null),
    ('ADJUVE', 'TOKIO', 15, null),
    ('André gomes dos santos', 'TOKIO', 15, null),
    ('ALBERTO SOARES', 'TOKIO', 15, null),
    ('ALEXANDRE CARNEIRO', 'TOKIO', 15, null),
    ('ALEXANDRE DUHZ', 'TOKIO', 15, null),
    ('AMARANTE E GANDARA', 'TOKIO', 15, null),
    ('ANA CARLA ROSSI REZENDE', 'TOKIO', 15, null),
    ('BACELLAR', 'TOKIO', 15, null),
    ('BALCARCE', 'TOKIO', 15, null),
    ('BASE', 'TOKIO', 15, null),
    ('BCM', 'TOKIO', 15, null),
    ('BROTHERHOOD', 'TOKIO', 15, null),
    ('BS MACHADO', 'TOKIO', 15, null),
    ('CARLOS ADOLFO', 'TOKIO', 15, null),
    ('CASA CAPRI', 'TOKIO', 15, null),
    ('CENTRO JURIDICO', 'TOKIO', 15, null),
    ('CLAUDIA CARVALHO', 'TOKIO', 15, null),
    ('CRISTIANO ALVES', 'TOKIO', 15, null),
    ('CHEZ BRASIL', 'TOKIO', 15, null),
    ('DOMENICI', 'TOKIO', 15, null),
    ('DCS', 'TOKIO', 15, null),
    ('EXCLUSIVA', 'TOKIO', 15, null),
    ('ENJOY', 'TOKIO', 15, null),
    ('EXPAN', 'TOKIO', 15, null),
    ('FLAVIO BRAGA MONTEIRO', 'TOKIO', 15, null),
    ('FR COSTA', 'TOKIO', 15, null),
    ('GAUCHO IMOVEIS', 'TOKIO', 15, null),
    ('GRACE GONCALVES', 'TOKIO', 15, null),
    ('HUMBERTO CANALE', 'TOKIO', 15, null),
    ('HÉLIO HIBAS (HC CONSULTORIA)', 'TOKIO', 15, null),
    ('IMOBARRA (VITAL DIAS)', 'TOKIO', 15, null),
    ('IMOVEL LIVRE', 'TOKIO', 15, null),
    ('IMOVELUM PLATAFORMA IMOBILIARIA LTDA', 'TOKIO', 15, null),
    ('I9 INOVE', 'TOKIO', 15, null),
    ('JIUSTI IMOVEIS CONDOMINIOS', 'TOKIO', 15, null),
    ('JOAO MARCO BESSA', 'TOKIO', 15, null),
    ('JOAO MARTINS', 'TOKIO', 15, null),
    ('JSJ', 'TOKIO', 15, null),
    ('VERITAS IMOVEIS SOLUÇÕES', 'TOKIO', 15, null),
    ('LAGORIO', 'TOKIO', 15, null),
    ('LIBERTY ADM (722805)', 'TOKIO', 15, null),
    ('LIVE IMOVEIS', 'TOKIO', 15, null),
    ('LÍDER RIO', 'TOKIO', 15, null),
    ('LOURENCO', 'TOKIO', 15, null),
    ('LUIS ROMEIRO', 'TOKIO', 15, null),
    ('LUIZ FLAVIO', 'TOKIO', 15, null),
    ('LUMAR', 'TOKIO', 15, null),
    ('M V R', 'TOKIO', 15, null),
    ('MAPA', 'TOKIO', 15, null),
    ('MARREIROS IMOVEIS', 'TOKIO', 15, null),
    ('MATERDRADE', 'TOKIO', 15, null),
    ('MAX BROKERS', 'TOKIO', 15, null),
    ('METHODUS', 'TOKIO', 15, null),
    ('MONTE ALEGRE EMPREENDIMENTOS', 'TOKIO', 15, null),
    ('MONTE ALEGRE GESTÃO', 'TOKIO', 15, null),
    ('MONTENEGRO', 'TOKIO', 15, null),
    ('MORAES E VECCHI', 'TOKIO', 15, null),
    ('NELIO GOMES', 'TOKIO', 15, null),
    ('OBJETIVA', 'TOKIO', 15, null),
    ('OKRE', 'TOKIO', 15, null),
    ('PAULO SAMPAIO', 'TOKIO', 15, null),
    ('PINTAS IMOVEIS', 'TOKIO', 15, null),
    ('R N P FORMOSO CORRETAGEM', 'TOKIO', 15, null),
    ('SPECIAL RESIDENCE', 'TOKIO', 15, null),
    ('R&SA GESTÃO', 'TOKIO', 15, null),
    ('RCJ (ROGERIO CASSIANO)', 'TOKIO', 15, null),
    ('RDJ', 'TOKIO', 15, null),
    ('REAL UP', 'TOKIO', 15, null),
    ('RHIAN AZEREDO', 'TOKIO', 15, null),
    ('RIBAS HP', 'TOKIO', 15, null),
    ('RJ VILLELA', 'TOKIO', 15, null),
    ('RODRIGO ARRUDA', 'TOKIO', 15, null),
    ('R SOARES', 'TOKIO', 15, null),
    ('SCASTTRO IMOVEIS', 'TOKIO', 15, null),
    ('SELLING', 'TOKIO', 15, null),
    ('SELMA MARIA CARDOSO', 'TOKIO', 15, null),
    ('SM ADM', 'TOKIO', 15, null),
    ('SPIN', 'TOKIO', 15, null),
    ('SUA CASA DIGITAL', 'TOKIO', 15, null),
    ('TAGS IMOVEIS', 'TOKIO', 15, null),
    ('TRATTO IMOVEIS', 'TOKIO', 15, null),
    ('TRAVASSOS', 'TOKIO', 15, null),
    ('SERRA REAL', 'TOKIO', 15, null),
    ('TWP', 'TOKIO', 15, null),
    ('VÂNIA AMARAL', 'TOKIO', 15, null),
    ('VENDABLE', 'TOKIO', 15, null),
    ('VIVIAN MANSUR', 'TOKIO', 15, null),
    ('MTT 100', 'TOKIO', 17, null),
    ('MTT 300', 'TOKIO', 17, null),
    ('MTT 500', 'TOKIO', 17, null),
    ('MTT 600', 'TOKIO', 17, null),
    ('ADAK', 'TOKIO', 20, null),
    ('EXPAN', 'TOKIO', 20, null),
    ('NATELMA', 'TOKIO', 20, null),
    ('PAULA ADRIANA', 'TOKIO', 20, null),
    ('RAFAEL PENNA', 'TOKIO', 20, null),
    ('TDC', 'TOKIO', 20, null),
    ('VALVERDE E FERNANDES', 'TOKIO', 20, null),
    ('BSJ', 'TOKIO', 21, null),
    ('MICHELE FREITAS', 'TOKIO', 22, null),
    ('ACVM', 'TOKIO', 23, null),
    ('SILVÉRIO IMÓVEIS', 'TOKIO', 23, null),
    ('ANDREIA BAFFA', 'TOKIO', 23, null),
    ('IMOPRET', 'TOKIO', 23, null),
    ('LUMAR', 'TOKIO', 23, null),
    ('LIBERTY ADM (614835)', 'TOKIO', 28, null),
    ('WALKER', 'TOKIO', 28, null),
    ('ACESSE', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('ACHARIMOVEIS', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('ACOM', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('ADJENE', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('ADJUVE', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('ADMINISTRADORA FONTE DE ELIM', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('ALEFE', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('ALEXANDRE DUHZ', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('BACELLAR', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('BALCARCE', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('BARPEN', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('BROTHERHOOD', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('BASE', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('BCM', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('BRASIL IMOVEIS', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('BSJ', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('CANFIELD', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('CHIEZA (CENTRO JURÍDICO)', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('CARLOS ADOLFO', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('CARMO E FLORES', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('CLAUDIA BORGES', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('CHEZ BRASIL', 'PORTO FIANÇA', 10, 'O2 Cap'),
    ('CLAUDIA CARVALHO', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('CRUZEIRO DO SUL', 'PORTO FIANÇA', 10, 'O2 Cap'),
    ('DAHER', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('DANIEL', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('DCS', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('DENIS JOSE DE LIMA SOUSA', 'PORTO FIANÇA', 10, 'O2 Cap'),
    ('ELIZABETH PINHO', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('ESTRUTURA', 'PORTO FIANÇA', 10, 'O2 Cap'),
    ('EXCLUSIVA', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('EXPAN', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('ENJOY', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('GAUCHO IMOVEIS', 'PORTO FIANÇA', 10, 'O2 Cap'),
    ('GNST', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('GQT', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('HUMBERTO CANALE', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('IMOBARRA', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('IMOPRET', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('IMOVEL LIVRE', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('INTEX', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('IURI', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('JGM DE MESQUITA', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('LLF (JUST FOR YOU)', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('JIUSTI IMOVEIS', 'PORTO FIANÇA', 10, 'O2 Cap'),
    ('JOAO MARTINS SOBRINHO', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('LIBERTY ADMINISTRADORA DE BENS LTDA', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('LIDER RIO', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('LUIS ROMEIRO', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('LUMAR', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('LUPE', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('MARCOS CARVALHO IMOVEIS ( CARVALHO IMOVEIS)', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('MARCUS DREHER IMOVEIS', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('MARCUS LARANJA DREHER', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('MARISTELA ROCHA DA SILVA', 'PORTO FIANÇA', 10, 'O2 Cap'),
    ('METHODUS', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('MONTENEGRO', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('MVR BARBOSA', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('NOVA MORADA | RJ VILLELA', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('OBJETIVA', 'PORTO FIANÇA', 10, 'O2 Cap'),
    ('PAULA ADRIANA', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('PROCED ADM', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('PROCED LOPES', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('R SOARES', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('R046', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('RAFAEL PENNA', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('RAMIRO SÁ', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('RAS ADM (EGIDE)', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('RAUL LOPES', 'PORTO FIANÇA', 10, 'O2 Cap'),
    ('REAL IMÓVEIS', 'PORTO FIANÇA', 10, 'O2 Cap'),
    ('REAL UP', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('RENATO DE SOUSA LOPES', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('RIO CAPITAL', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('RODRIGO NUNES', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('SANDRA XAVIER', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('SCASTTRO', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('SENADOR', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('SM IMOVEIS', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('SPECIAL', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('SPIN', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('TAGS IMOVEIS', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('TERUSZKIN', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('TORRES CINTRA', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('TRAVASSOS', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('VALVERDE E FERNANDES', 'PORTO FIANÇA', 10, 'O2 Cap'),
    ('VIRTHUS', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('VIVIAN MANSUR', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('WALKER', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('FLAVIA BECK', 'PORTO RE', 15, 'O2 Seguros'),
    ('MARCIA SIMOR PANI', 'PORTO RE', 15, 'O2 Seguros'),
    ('HUMBERTO CANALE', 'PORTO RE', 15, 'O2 Seguros'),
    ('JOSE CARLOS LOPES', 'PORTO RE', 15, 'O2 Seguros'),
    ('KS CONSULTORIA', 'PORTO RE', 15, 'O2 Seguros'),
    ('ROBERTO R C FILHO', 'PORTO RE', 15, 'O2 Seguros'),
    ('SMART ADM', 'PORTO RE', 15, 'O2 Seguros'),
    ('TIAGO SANTOS STORTI', 'PORTO RE', 15, 'O2 Seguros'),
    ('SPECIAL', 'PORTO RE', 15, 'O2 Seguros'),
    ('2MX CONSULTORIA', 'TOO', null, 'O2 Seguros'),
    ('ACERVO CARIOCA', 'TOO', null, 'O2 Cap'),
    ('ADJUVE', 'TOO', null, 'O2 Seguros'),
    ('ADILSON BRAZ', 'TOO', null, 'O2 Cap'),
    ('BACELLAR', 'TOO', null, 'O2 Seguros'),
    ('BERGE IMOVEIS', 'TOO', null, 'O2 Seguros'),
    ('BROTHERHOOD', 'TOO', null, 'O2 Cap'),
    ('CARLOS BECKER', 'TOO', null, 'O2 Seguros'),
    ('CELTHA CONSULTORIA', 'TOO', null, 'O2 Seguros'),
    ('CENTRO JURIDICO', 'TOO', null, 'O2 Cap'),
    ('CLAUDIA DANTAS', 'TOO', null, 'O2 Cap'),
    ('DCS', 'TOO', null, 'O2 Seguros'),
    ('EXPAN ADM', 'TOO', null, 'O2 Cap'),
    ('FRANKLIN RANGEL', 'TOO', null, 'O2 Seguros'),
    ('IMOBILIARIA HUMBERTO CANALE', 'TOO', null, 'O2 Seguros'),
    ('IMOVEL LIVRE', 'TOO', null, 'O2 Seguros'),
    ('INTEX CONSULTORIA', 'TOO', null, 'O2 Seguros'),
    ('IURI CORRETAGEM', 'TOO', null, 'O2 Seguros'),
    ('JGM', 'TOO', null, 'O2 Cap'),
    ('JOAO MARTINS', 'TOO', null, 'O2 Seguros'),
    ('LLF ASSESSORIA', 'TOO', null, 'O2 Seguros'),
    ('LUCIENE JIUSTI', 'TOO', null, 'O2 Seguros'),
    ('LUMAR ADMINISTRACAO', 'TOO', null, 'O2 Seguros'),
    ('LUPE ADMINISTRACAO', 'TOO', null, 'O2 Seguros'),
    ('MAPA ADM', 'TOO', null, 'O2 Seguros'),
    ('MONTE ALEGRE', 'TOO', null, 'O2 Seguros'),
    ('MONTE ALEGRE GESTAO', 'TOO', null, 'O2 Cap'),
    ('PAULA ADRIANA', 'TOO', null, 'O2 Seguros'),
    ('PROCED ADM', 'TOO', null, 'O2 Seguros'),
    ('PROCED LOPES', 'TOO', null, 'O2 Seguros'),
    ('R&SA', 'TOO', null, 'O2 Seguros'),
    ('RAMIRO AUGUSTO', 'TOO', null, 'O2 Seguros'),
    ('RIO CAPITAL', 'TOO', null, 'O2 Seguros'),
    ('SANDRA XAVIER', 'TOO', null, 'O2 Seguros'),
    ('SERPA (SPIN)', 'TOO', null, 'O2 Seguros'),
    ('SILVERIO IMOVEIS', 'TOO', null, 'O2 Seguros'),
    ('SPECIAL', 'TOO', null, 'O2 Cap'),
    ('TIAGO SANTOS', 'TOO', null, 'O2 Cap'),
    ('VANIA AMARAL', 'TOO', null, 'O2 Cap'),
    ('WALKER CORRETORA', 'TOO', null, 'O2 Cap'),
    ('CLEITON ALVES', 'TOO', null, 'O2 Seguros'),
    ('HELIO RIBAS', 'TOO', null, 'O2 Cap'),
    ('A. BISBOCCI', 'POTTENCIAL', 15, null),
    ('ACERVO CARIOCA', 'POTTENCIAL', 15, null),
    ('ACESSE', 'POTTENCIAL', 15, null),
    ('ADJENE', 'POTTENCIAL', 15, null),
    ('ADJUVE', 'POTTENCIAL', 15, null),
    ('ALEFE', 'POTTENCIAL', 15, null),
    ('ALFREDO GUILHERME', 'POTTENCIAL', 15, null),
    ('ANEXO ADM', 'POTTENCIAL', 15, null),
    ('BARPEN', 'POTTENCIAL', 15, null),
    ('BASE', 'POTTENCIAL', 15, null),
    ('BERGE', 'POTTENCIAL', 15, null),
    ('BROTHERHOOD', 'POTTENCIAL', 15, null),
    ('BSJ', 'POTTENCIAL', 15, null),
    ('CLAUDIA BORGES', 'POTTENCIAL', 15, null),
    ('CANFILD E CANFILD', 'POTTENCIAL', 15, null),
    ('DCS', 'POTTENCIAL', 15, null),
    ('ENJOY', 'POTTENCIAL', 15, null),
    ('ESTRUTURA', 'POTTENCIAL', 15, null),
    ('EXCLUSIVA', 'POTTENCIAL', 15, null),
    ('HUMBERTO CANALE', 'POTTENCIAL', 15, null),
    ('IMOBARRA (VITAL DIAS)', 'POTTENCIAL', 15, null),
    ('IMOVEL LIVRE', 'POTTENCIAL', 15, null),
    ('I9', 'POTTENCIAL', 15, null),
    ('JMARTINS', 'POTTENCIAL', 15, null),
    ('JUST FOR YOU (LLF ASSESSORIA)', 'POTTENCIAL', 15, null),
    ('LIDER RIO', 'POTTENCIAL', 15, null),
    ('LSL ASSESORIA', 'POTTENCIAL', 15, null),
    ('LUPE', 'POTTENCIAL', 15, null),
    ('MAC CONSULTORIA', 'POTTENCIAL', 15, null),
    ('MAPA', 'POTTENCIAL', 15, null),
    ('MARCUS DREHER', 'POTTENCIAL', 15, null),
    ('METHODUS', 'POTTENCIAL', 15, null),
    ('MONTE ALEGRE', 'POTTENCIAL', 15, null),
    ('OBJETIVA', 'POTTENCIAL', 15, null),
    ('PAULA ADRIANA (GRÃO PARÁ)', 'POTTENCIAL', 15, null),
    ('PROCED LOPES', 'POTTENCIAL', 15, null),
    ('R&SA GESTAO', 'POTTENCIAL', 15, null),
    ('R046', 'POTTENCIAL', 15, null),
    ('RCJ IMÓVEIS - ROGÉRIO CASSIANO', 'POTTENCIAL', 15, null),
    ('RDJ', 'POTTENCIAL', 15, null),
    ('RAMIRO SA', 'POTTENCIAL', 15, null),
    ('SPIN', 'POTTENCIAL', 15, null),
    ('SPECIAL', 'POTTENCIAL', 15, null),
    ('SILVERIO IMOVEIS', 'POTTENCIAL', 15, null),
    ('TORRES CINTRA', 'POTTENCIAL', 15, null),
    ('TRAVASSOS E ACHAR IMOVEIS', 'POTTENCIAL', 15, null),
    ('VIZU', 'POTTENCIAL', 15, null),
    ('FERNANDO OLIVEIRA DE PAIVA', 'POTTENCIAL', 15, null),
    ('MONTE ALEGRE GESTAO', 'YELUM', 10, null),
    ('MONTE ALEGRE IMOVEIS', 'YELUM', 10, null),
    ('LIBERTY CENTRO', 'YELUM', 10, null),
    ('ESTRUTURA', 'YELUM', 15, null),
    ('REAL UP', 'YELUM', 15, null),
    ('SPECIAL RESIDENCE', 'YELUM', 15, null),
    ('ACESSE', 'YELUM', 20, null),
    ('L3', 'YELUM', 20, null),
    ('PRIVILEGIO', 'YELUM', 20, null)
)
-- Atualiza quem já foi resolvido (tem imobiliaria_id de verdade)
update faturas_esperadas fe
set dia_vencimento = coalesce(d.dia_vencimento, fe.dia_vencimento),
    cnpj_o2 = coalesce(d.cnpj_o2, fe.cnpj_o2)
from dados d
join imobiliarias_conhecidas ic on upper(trim(ic.nome)) = upper(trim(d.nome_planilha))
join imobiliarias i on i.cnpj = ic.cnpj
where fe.imobiliaria_id = i.id and fe.seguradora = d.seguradora;

-- Atualiza quem ainda está pendente de CNPJ (nome_provisorio)
with dados(nome_planilha, seguradora, dia_vencimento, cnpj_o2) as (
  values
    ('PROMOVEL IMOBILIÁRIA LTDA', 'TOKIO', 8, null),
    ('BERGE', 'TOKIO', 9, null),
    ('DAHER', 'TOKIO', 9, null),
    ('RIO CAPITAL', 'TOKIO', 9, null),
    ('PROCED LOPES', 'TOKIO', 10, null),
    ('ACERVO CARIOCA', 'TOKIO', 15, null),
    ('ACESSE IMÓVEL RJ', 'TOKIO', 15, null),
    ('ADILSON BRAZ', 'TOKIO', 15, null),
    ('ADJUVE', 'TOKIO', 15, null),
    ('André gomes dos santos', 'TOKIO', 15, null),
    ('ALBERTO SOARES', 'TOKIO', 15, null),
    ('ALEXANDRE CARNEIRO', 'TOKIO', 15, null),
    ('ALEXANDRE DUHZ', 'TOKIO', 15, null),
    ('AMARANTE E GANDARA', 'TOKIO', 15, null),
    ('ANA CARLA ROSSI REZENDE', 'TOKIO', 15, null),
    ('BACELLAR', 'TOKIO', 15, null),
    ('BALCARCE', 'TOKIO', 15, null),
    ('BASE', 'TOKIO', 15, null),
    ('BCM', 'TOKIO', 15, null),
    ('BROTHERHOOD', 'TOKIO', 15, null),
    ('BS MACHADO', 'TOKIO', 15, null),
    ('CARLOS ADOLFO', 'TOKIO', 15, null),
    ('CASA CAPRI', 'TOKIO', 15, null),
    ('CENTRO JURIDICO', 'TOKIO', 15, null),
    ('CLAUDIA CARVALHO', 'TOKIO', 15, null),
    ('CRISTIANO ALVES', 'TOKIO', 15, null),
    ('CHEZ BRASIL', 'TOKIO', 15, null),
    ('DOMENICI', 'TOKIO', 15, null),
    ('DCS', 'TOKIO', 15, null),
    ('EXCLUSIVA', 'TOKIO', 15, null),
    ('ENJOY', 'TOKIO', 15, null),
    ('EXPAN', 'TOKIO', 15, null),
    ('FLAVIO BRAGA MONTEIRO', 'TOKIO', 15, null),
    ('FR COSTA', 'TOKIO', 15, null),
    ('GAUCHO IMOVEIS', 'TOKIO', 15, null),
    ('GRACE GONCALVES', 'TOKIO', 15, null),
    ('HUMBERTO CANALE', 'TOKIO', 15, null),
    ('HÉLIO HIBAS (HC CONSULTORIA)', 'TOKIO', 15, null),
    ('IMOBARRA (VITAL DIAS)', 'TOKIO', 15, null),
    ('IMOVEL LIVRE', 'TOKIO', 15, null),
    ('IMOVELUM PLATAFORMA IMOBILIARIA LTDA', 'TOKIO', 15, null),
    ('I9 INOVE', 'TOKIO', 15, null),
    ('JIUSTI IMOVEIS CONDOMINIOS', 'TOKIO', 15, null),
    ('JOAO MARCO BESSA', 'TOKIO', 15, null),
    ('JOAO MARTINS', 'TOKIO', 15, null),
    ('JSJ', 'TOKIO', 15, null),
    ('VERITAS IMOVEIS SOLUÇÕES', 'TOKIO', 15, null),
    ('LAGORIO', 'TOKIO', 15, null),
    ('LIBERTY ADM (722805)', 'TOKIO', 15, null),
    ('LIVE IMOVEIS', 'TOKIO', 15, null),
    ('LÍDER RIO', 'TOKIO', 15, null),
    ('LOURENCO', 'TOKIO', 15, null),
    ('LUIS ROMEIRO', 'TOKIO', 15, null),
    ('LUIZ FLAVIO', 'TOKIO', 15, null),
    ('LUMAR', 'TOKIO', 15, null),
    ('M V R', 'TOKIO', 15, null),
    ('MAPA', 'TOKIO', 15, null),
    ('MARREIROS IMOVEIS', 'TOKIO', 15, null),
    ('MATERDRADE', 'TOKIO', 15, null),
    ('MAX BROKERS', 'TOKIO', 15, null),
    ('METHODUS', 'TOKIO', 15, null),
    ('MONTE ALEGRE EMPREENDIMENTOS', 'TOKIO', 15, null),
    ('MONTE ALEGRE GESTÃO', 'TOKIO', 15, null),
    ('MONTENEGRO', 'TOKIO', 15, null),
    ('MORAES E VECCHI', 'TOKIO', 15, null),
    ('NELIO GOMES', 'TOKIO', 15, null),
    ('OBJETIVA', 'TOKIO', 15, null),
    ('OKRE', 'TOKIO', 15, null),
    ('PAULO SAMPAIO', 'TOKIO', 15, null),
    ('PINTAS IMOVEIS', 'TOKIO', 15, null),
    ('R N P FORMOSO CORRETAGEM', 'TOKIO', 15, null),
    ('SPECIAL RESIDENCE', 'TOKIO', 15, null),
    ('R&SA GESTÃO', 'TOKIO', 15, null),
    ('RCJ (ROGERIO CASSIANO)', 'TOKIO', 15, null),
    ('RDJ', 'TOKIO', 15, null),
    ('REAL UP', 'TOKIO', 15, null),
    ('RHIAN AZEREDO', 'TOKIO', 15, null),
    ('RIBAS HP', 'TOKIO', 15, null),
    ('RJ VILLELA', 'TOKIO', 15, null),
    ('RODRIGO ARRUDA', 'TOKIO', 15, null),
    ('R SOARES', 'TOKIO', 15, null),
    ('SCASTTRO IMOVEIS', 'TOKIO', 15, null),
    ('SELLING', 'TOKIO', 15, null),
    ('SELMA MARIA CARDOSO', 'TOKIO', 15, null),
    ('SM ADM', 'TOKIO', 15, null),
    ('SPIN', 'TOKIO', 15, null),
    ('SUA CASA DIGITAL', 'TOKIO', 15, null),
    ('TAGS IMOVEIS', 'TOKIO', 15, null),
    ('TRATTO IMOVEIS', 'TOKIO', 15, null),
    ('TRAVASSOS', 'TOKIO', 15, null),
    ('SERRA REAL', 'TOKIO', 15, null),
    ('TWP', 'TOKIO', 15, null),
    ('VÂNIA AMARAL', 'TOKIO', 15, null),
    ('VENDABLE', 'TOKIO', 15, null),
    ('VIVIAN MANSUR', 'TOKIO', 15, null),
    ('MTT 100', 'TOKIO', 17, null),
    ('MTT 300', 'TOKIO', 17, null),
    ('MTT 500', 'TOKIO', 17, null),
    ('MTT 600', 'TOKIO', 17, null),
    ('ADAK', 'TOKIO', 20, null),
    ('EXPAN', 'TOKIO', 20, null),
    ('NATELMA', 'TOKIO', 20, null),
    ('PAULA ADRIANA', 'TOKIO', 20, null),
    ('RAFAEL PENNA', 'TOKIO', 20, null),
    ('TDC', 'TOKIO', 20, null),
    ('VALVERDE E FERNANDES', 'TOKIO', 20, null),
    ('BSJ', 'TOKIO', 21, null),
    ('MICHELE FREITAS', 'TOKIO', 22, null),
    ('ACVM', 'TOKIO', 23, null),
    ('SILVÉRIO IMÓVEIS', 'TOKIO', 23, null),
    ('ANDREIA BAFFA', 'TOKIO', 23, null),
    ('IMOPRET', 'TOKIO', 23, null),
    ('LUMAR', 'TOKIO', 23, null),
    ('LIBERTY ADM (614835)', 'TOKIO', 28, null),
    ('WALKER', 'TOKIO', 28, null),
    ('ACESSE', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('ACHARIMOVEIS', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('ACOM', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('ADJENE', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('ADJUVE', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('ADMINISTRADORA FONTE DE ELIM', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('ALEFE', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('ALEXANDRE DUHZ', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('BACELLAR', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('BALCARCE', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('BARPEN', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('BROTHERHOOD', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('BASE', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('BCM', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('BRASIL IMOVEIS', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('BSJ', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('CANFIELD', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('CHIEZA (CENTRO JURÍDICO)', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('CARLOS ADOLFO', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('CARMO E FLORES', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('CLAUDIA BORGES', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('CHEZ BRASIL', 'PORTO FIANÇA', 10, 'O2 Cap'),
    ('CLAUDIA CARVALHO', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('CRUZEIRO DO SUL', 'PORTO FIANÇA', 10, 'O2 Cap'),
    ('DAHER', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('DANIEL', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('DCS', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('DENIS JOSE DE LIMA SOUSA', 'PORTO FIANÇA', 10, 'O2 Cap'),
    ('ELIZABETH PINHO', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('ESTRUTURA', 'PORTO FIANÇA', 10, 'O2 Cap'),
    ('EXCLUSIVA', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('EXPAN', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('ENJOY', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('GAUCHO IMOVEIS', 'PORTO FIANÇA', 10, 'O2 Cap'),
    ('GNST', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('GQT', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('HUMBERTO CANALE', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('IMOBARRA', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('IMOPRET', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('IMOVEL LIVRE', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('INTEX', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('IURI', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('JGM DE MESQUITA', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('LLF (JUST FOR YOU)', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('JIUSTI IMOVEIS', 'PORTO FIANÇA', 10, 'O2 Cap'),
    ('JOAO MARTINS SOBRINHO', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('LIBERTY ADMINISTRADORA DE BENS LTDA', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('LIDER RIO', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('LUIS ROMEIRO', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('LUMAR', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('LUPE', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('MARCOS CARVALHO IMOVEIS ( CARVALHO IMOVEIS)', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('MARCUS DREHER IMOVEIS', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('MARCUS LARANJA DREHER', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('MARISTELA ROCHA DA SILVA', 'PORTO FIANÇA', 10, 'O2 Cap'),
    ('METHODUS', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('MONTENEGRO', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('MVR BARBOSA', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('NOVA MORADA | RJ VILLELA', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('OBJETIVA', 'PORTO FIANÇA', 10, 'O2 Cap'),
    ('PAULA ADRIANA', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('PROCED ADM', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('PROCED LOPES', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('R SOARES', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('R046', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('RAFAEL PENNA', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('RAMIRO SÁ', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('RAS ADM (EGIDE)', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('RAUL LOPES', 'PORTO FIANÇA', 10, 'O2 Cap'),
    ('REAL IMÓVEIS', 'PORTO FIANÇA', 10, 'O2 Cap'),
    ('REAL UP', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('RENATO DE SOUSA LOPES', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('RIO CAPITAL', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('RODRIGO NUNES', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('SANDRA XAVIER', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('SCASTTRO', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('SENADOR', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('SM IMOVEIS', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('SPECIAL', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('SPIN', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('TAGS IMOVEIS', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('TERUSZKIN', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('TORRES CINTRA', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('TRAVASSOS', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('VALVERDE E FERNANDES', 'PORTO FIANÇA', 10, 'O2 Cap'),
    ('VIRTHUS', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('VIVIAN MANSUR', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('WALKER', 'PORTO FIANÇA', 10, 'O2 Seguros'),
    ('FLAVIA BECK', 'PORTO RE', 15, 'O2 Seguros'),
    ('MARCIA SIMOR PANI', 'PORTO RE', 15, 'O2 Seguros'),
    ('HUMBERTO CANALE', 'PORTO RE', 15, 'O2 Seguros'),
    ('JOSE CARLOS LOPES', 'PORTO RE', 15, 'O2 Seguros'),
    ('KS CONSULTORIA', 'PORTO RE', 15, 'O2 Seguros'),
    ('ROBERTO R C FILHO', 'PORTO RE', 15, 'O2 Seguros'),
    ('SMART ADM', 'PORTO RE', 15, 'O2 Seguros'),
    ('TIAGO SANTOS STORTI', 'PORTO RE', 15, 'O2 Seguros'),
    ('SPECIAL', 'PORTO RE', 15, 'O2 Seguros'),
    ('2MX CONSULTORIA', 'TOO', null, 'O2 Seguros'),
    ('ACERVO CARIOCA', 'TOO', null, 'O2 Cap'),
    ('ADJUVE', 'TOO', null, 'O2 Seguros'),
    ('ADILSON BRAZ', 'TOO', null, 'O2 Cap'),
    ('BACELLAR', 'TOO', null, 'O2 Seguros'),
    ('BERGE IMOVEIS', 'TOO', null, 'O2 Seguros'),
    ('BROTHERHOOD', 'TOO', null, 'O2 Cap'),
    ('CARLOS BECKER', 'TOO', null, 'O2 Seguros'),
    ('CELTHA CONSULTORIA', 'TOO', null, 'O2 Seguros'),
    ('CENTRO JURIDICO', 'TOO', null, 'O2 Cap'),
    ('CLAUDIA DANTAS', 'TOO', null, 'O2 Cap'),
    ('DCS', 'TOO', null, 'O2 Seguros'),
    ('EXPAN ADM', 'TOO', null, 'O2 Cap'),
    ('FRANKLIN RANGEL', 'TOO', null, 'O2 Seguros'),
    ('IMOBILIARIA HUMBERTO CANALE', 'TOO', null, 'O2 Seguros'),
    ('IMOVEL LIVRE', 'TOO', null, 'O2 Seguros'),
    ('INTEX CONSULTORIA', 'TOO', null, 'O2 Seguros'),
    ('IURI CORRETAGEM', 'TOO', null, 'O2 Seguros'),
    ('JGM', 'TOO', null, 'O2 Cap'),
    ('JOAO MARTINS', 'TOO', null, 'O2 Seguros'),
    ('LLF ASSESSORIA', 'TOO', null, 'O2 Seguros'),
    ('LUCIENE JIUSTI', 'TOO', null, 'O2 Seguros'),
    ('LUMAR ADMINISTRACAO', 'TOO', null, 'O2 Seguros'),
    ('LUPE ADMINISTRACAO', 'TOO', null, 'O2 Seguros'),
    ('MAPA ADM', 'TOO', null, 'O2 Seguros'),
    ('MONTE ALEGRE', 'TOO', null, 'O2 Seguros'),
    ('MONTE ALEGRE GESTAO', 'TOO', null, 'O2 Cap'),
    ('PAULA ADRIANA', 'TOO', null, 'O2 Seguros'),
    ('PROCED ADM', 'TOO', null, 'O2 Seguros'),
    ('PROCED LOPES', 'TOO', null, 'O2 Seguros'),
    ('R&SA', 'TOO', null, 'O2 Seguros'),
    ('RAMIRO AUGUSTO', 'TOO', null, 'O2 Seguros'),
    ('RIO CAPITAL', 'TOO', null, 'O2 Seguros'),
    ('SANDRA XAVIER', 'TOO', null, 'O2 Seguros'),
    ('SERPA (SPIN)', 'TOO', null, 'O2 Seguros'),
    ('SILVERIO IMOVEIS', 'TOO', null, 'O2 Seguros'),
    ('SPECIAL', 'TOO', null, 'O2 Cap'),
    ('TIAGO SANTOS', 'TOO', null, 'O2 Cap'),
    ('VANIA AMARAL', 'TOO', null, 'O2 Cap'),
    ('WALKER CORRETORA', 'TOO', null, 'O2 Cap'),
    ('CLEITON ALVES', 'TOO', null, 'O2 Seguros'),
    ('HELIO RIBAS', 'TOO', null, 'O2 Cap'),
    ('A. BISBOCCI', 'POTTENCIAL', 15, null),
    ('ACERVO CARIOCA', 'POTTENCIAL', 15, null),
    ('ACESSE', 'POTTENCIAL', 15, null),
    ('ADJENE', 'POTTENCIAL', 15, null),
    ('ADJUVE', 'POTTENCIAL', 15, null),
    ('ALEFE', 'POTTENCIAL', 15, null),
    ('ALFREDO GUILHERME', 'POTTENCIAL', 15, null),
    ('ANEXO ADM', 'POTTENCIAL', 15, null),
    ('BARPEN', 'POTTENCIAL', 15, null),
    ('BASE', 'POTTENCIAL', 15, null),
    ('BERGE', 'POTTENCIAL', 15, null),
    ('BROTHERHOOD', 'POTTENCIAL', 15, null),
    ('BSJ', 'POTTENCIAL', 15, null),
    ('CLAUDIA BORGES', 'POTTENCIAL', 15, null),
    ('CANFILD E CANFILD', 'POTTENCIAL', 15, null),
    ('DCS', 'POTTENCIAL', 15, null),
    ('ENJOY', 'POTTENCIAL', 15, null),
    ('ESTRUTURA', 'POTTENCIAL', 15, null),
    ('EXCLUSIVA', 'POTTENCIAL', 15, null),
    ('HUMBERTO CANALE', 'POTTENCIAL', 15, null),
    ('IMOBARRA (VITAL DIAS)', 'POTTENCIAL', 15, null),
    ('IMOVEL LIVRE', 'POTTENCIAL', 15, null),
    ('I9', 'POTTENCIAL', 15, null),
    ('JMARTINS', 'POTTENCIAL', 15, null),
    ('JUST FOR YOU (LLF ASSESSORIA)', 'POTTENCIAL', 15, null),
    ('LIDER RIO', 'POTTENCIAL', 15, null),
    ('LSL ASSESORIA', 'POTTENCIAL', 15, null),
    ('LUPE', 'POTTENCIAL', 15, null),
    ('MAC CONSULTORIA', 'POTTENCIAL', 15, null),
    ('MAPA', 'POTTENCIAL', 15, null),
    ('MARCUS DREHER', 'POTTENCIAL', 15, null),
    ('METHODUS', 'POTTENCIAL', 15, null),
    ('MONTE ALEGRE', 'POTTENCIAL', 15, null),
    ('OBJETIVA', 'POTTENCIAL', 15, null),
    ('PAULA ADRIANA (GRÃO PARÁ)', 'POTTENCIAL', 15, null),
    ('PROCED LOPES', 'POTTENCIAL', 15, null),
    ('R&SA GESTAO', 'POTTENCIAL', 15, null),
    ('R046', 'POTTENCIAL', 15, null),
    ('RCJ IMÓVEIS - ROGÉRIO CASSIANO', 'POTTENCIAL', 15, null),
    ('RDJ', 'POTTENCIAL', 15, null),
    ('RAMIRO SA', 'POTTENCIAL', 15, null),
    ('SPIN', 'POTTENCIAL', 15, null),
    ('SPECIAL', 'POTTENCIAL', 15, null),
    ('SILVERIO IMOVEIS', 'POTTENCIAL', 15, null),
    ('TORRES CINTRA', 'POTTENCIAL', 15, null),
    ('TRAVASSOS E ACHAR IMOVEIS', 'POTTENCIAL', 15, null),
    ('VIZU', 'POTTENCIAL', 15, null),
    ('FERNANDO OLIVEIRA DE PAIVA', 'POTTENCIAL', 15, null),
    ('MONTE ALEGRE GESTAO', 'YELUM', 10, null),
    ('MONTE ALEGRE IMOVEIS', 'YELUM', 10, null),
    ('LIBERTY CENTRO', 'YELUM', 10, null),
    ('ESTRUTURA', 'YELUM', 15, null),
    ('REAL UP', 'YELUM', 15, null),
    ('SPECIAL RESIDENCE', 'YELUM', 15, null),
    ('ACESSE', 'YELUM', 20, null),
    ('L3', 'YELUM', 20, null),
    ('PRIVILEGIO', 'YELUM', 20, null)
)
update faturas_esperadas fe
set dia_vencimento = coalesce(d.dia_vencimento, fe.dia_vencimento),
    cnpj_o2 = coalesce(d.cnpj_o2, fe.cnpj_o2)
from dados d
where fe.nome_provisorio = d.nome_planilha and fe.seguradora = d.seguradora;
