-- Reconciliação v6: corrige um erro da v5 -- a guarda de tamanho mínimo
-- (4 caracteres, criada pra evitar falso positivo tipo "AG") estava sendo
-- aplicada até em correspondências EXATAS, bloqueando nomes curtos legítimos
-- como "BCM", "DCS", "BSJ", "TDC" que batem certinho, letra por letra, com o
-- que já está cadastrado. Agora a guarda só vale pra correspondência parcial
-- (contém) -- exata nunca precisa de guarda, não tem risco de falso positivo.

with planilha (seguradora, parceiro, dia_vencimento, origem, observacao) as (
  values
    ('TOKIO', 'PROMOVEL IMOBILIÁRIA LTDA', 8, 'SegImob', 'locacao@imoveisponto.com.br'),
    ('TOKIO', 'BERGE', 9, 'SegImob', NULL::text),
    ('TOKIO', 'DAHER', 9, 'SegImob', NULL::text),
    ('TOKIO', 'RIO CAPITAL', 9, 'SegImob', NULL::text),
    ('TOKIO', 'PROCED LOPES', 10, 'SegImob', NULL::text),
    ('TOKIO', 'ACERVO CARIOCA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'ACESSE IMÓVEL RJ', 15, 'SegImob', 'ENVIAR WPP TAMBÉM'),
    ('TOKIO', 'ADILSON BRAZ', 15, 'SegImob', NULL::text),
    ('TOKIO', 'ADJUVE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'André gomes dos santos', 15, 'SegImob', 'andrerjgomes@gmail.com'),
    ('TOKIO', 'ALBERTO SOARES', 15, 'SegImob', NULL::text),
    ('TOKIO', 'ALEXANDRE CARNEIRO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'ALEXANDRE DUHZ', 15, 'SegImob', NULL::text),
    ('TOKIO', 'AMARANTE E GANDARA', 15, 'O2 Seguros', NULL::text),
    ('TOKIO', 'ANA CARLA ROSSI REZENDE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'BACELLAR', 15, 'SegImob', NULL::text),
    ('TOKIO', 'BALCARCE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'BASE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'BCM', 15, 'SegImob', NULL::text),
    ('TOKIO', 'BROTHERHOOD', 15, 'SegImob', NULL::text),
    ('TOKIO', 'BS MACHADO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'CARLOS ADOLFO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'CASA CAPRI', 15, 'SegImob', NULL::text),
    ('TOKIO', 'CENTRO JURIDICO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'CLAUDIA CARVALHO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'CRISTIANO ALVES', 15, 'SegImob', NULL::text),
    ('TOKIO', 'CHEZ BRASIL', 15, 'SegImob', NULL::text),
    ('TOKIO', 'DOMENICI', 15, 'SegImob', NULL::text),
    ('TOKIO', 'DCS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'EXCLUSIVA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'ENJOY', 15, 'SegImob', NULL::text),
    ('TOKIO', 'FLAVIO BRAGA MONTEIRO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'FR COSTA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'GAUCHO IMOVEIS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'GRACE GONCALVES', 15, 'SegImob', NULL::text),
    ('TOKIO', 'HUMBERTO CANALE', 15, 'SegImob', 'financeiro@canaleimoveis.com.br'),
    ('TOKIO', 'HÉLIO HIBAS (HC CONSULTORIA)', 15, 'SegImob', NULL::text),
    ('TOKIO', 'IMOBARRA (VITAL DIAS)', 15, 'SegImob', NULL::text),
    ('TOKIO', 'IMOVEL LIVRE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'IMOVELUM PLATAFORMA IMOBILIARIA LTDA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'I9 INOVE', 15, 'SegImob', 'ENVIAR WPP TAMBÉM gestao@inovesolucoescontabeis.com.br'),
    ('TOKIO', 'JIUSTI IMOVEIS CONDOMINIOS', 15, 'O2 Seguros', NULL::text),
    ('TOKIO', 'JOAO MARCO BESSA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'JOAO MARTINS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'JSJ', 15, 'SegImob', NULL::text),
    ('TOKIO', 'VERITAS IMOVEIS SOLUÇÕES', 15, 'SegImob', 'amitrano78@gmail.com'),
    ('TOKIO', 'LAGORIO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'LIBERTY ADM (722805)', 15, 'SegImob', NULL::text),
    ('TOKIO', 'LIVE IMOVEIS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'LÍDER RIO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'LOURENCO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'LUIS ROMEIRO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'LUIZ FLAVIO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'M V R', 15, 'SegImob', NULL::text),
    ('TOKIO', 'MAPA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'MARREIROS IMOVEIS', 15, 'SegImob', 'imoveismarreiros@gmail.com'),
    ('TOKIO', 'MATERDRADE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'MAX BROKERS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'METHODUS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'MONTE ALEGRE EMPREENDIMENTOS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'MONTE ALEGRE GESTÃO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'MONTENEGRO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'MORAES E VECCHI', 15, 'SegImob', NULL::text),
    ('TOKIO', 'NELIO GOMES', 15, 'SegImob', NULL::text),
    ('TOKIO', 'OBJETIVA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'OKRE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'PAULO SAMPAIO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'PINTAS IMOVEIS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'R N P FORMOSO CORRETAGEM', 15, 'SegImob', NULL::text),
    ('TOKIO', 'SPECIAL RESIDENCE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'R&SA GESTÃO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'RCJ (ROGERIO CASSIANO)', 15, 'SegImob', NULL::text),
    ('TOKIO', 'RDJ', 15, 'SegImob', NULL::text),
    ('TOKIO', 'REAL UP', 15, 'SegImob', NULL::text),
    ('TOKIO', 'RHIAN AZEREDO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'RIBAS HP', 15, 'O2 Seguros', NULL::text),
    ('TOKIO', 'RJ VILLELA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'RODRIGO ARRUDA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'R SOARES', 15, 'SegImob', 'guiporcaro@hotmail.com'),
    ('TOKIO', 'SCASTTRO IMOVEIS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'SELLING', 15, 'SegImob', NULL::text),
    ('TOKIO', 'SELMA MARIA CARDOSO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'SM ADM', 15, 'SegImob', NULL::text),
    ('TOKIO', 'SPIN', 15, 'SegImob', NULL::text),
    ('TOKIO', 'SUA CASA DIGITAL', 15, 'SegImob', NULL::text),
    ('TOKIO', 'TAGS IMOVEIS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'TRATTO IMOVEIS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'TRAVASSOS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'SERRA REAL', 15, 'SegImob', 'Serrarealimoveis@gmail.com'),
    ('TOKIO', 'TWP', 15, 'SegImob', NULL::text),
    ('TOKIO', 'VÂNIA AMARAL', 15, 'SegImob', NULL::text),
    ('TOKIO', 'VENDABLE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'VIVIAN MANSUR', 15, 'SegImob', 'Enviar pelo wpp também a partir de nov/25'),
    ('TOKIO', 'MTT 100', 17, 'SegImob', NULL::text),
    ('TOKIO', 'MTT 300', 17, 'SegImob', NULL::text),
    ('TOKIO', 'MTT 500', 17, 'SegImob', NULL::text),
    ('TOKIO', 'MTT 600', 17, 'SegImob', NULL::text),
    ('TOKIO', 'ADAK', 20, 'SegImob', NULL::text),
    ('TOKIO', 'NATELMA', 20, 'O2 Seguros', NULL::text),
    ('TOKIO', 'PAULA ADRIANA', 20, 'SegImob', NULL::text),
    ('TOKIO', 'RAFAEL PENNA', 20, 'SegImob', NULL::text),
    ('TOKIO', 'TDC', 20, 'O2 Seguros', NULL::text),
    ('TOKIO', 'VALVERDE E FERNANDES', 20, 'SegImob', NULL::text),
    ('TOKIO', 'BSJ', 21, 'SegImob', NULL::text),
    ('TOKIO', 'MICHELE FREITAS', 22, 'O2 Seguros', NULL::text),
    ('TOKIO', 'ACVM', 23, 'SegImob', NULL::text),
    ('TOKIO', 'SILVÉRIO IMÓVEIS', 23, 'SegImob', 'financeiro@silverioimoveis.com.br'),
    ('TOKIO', 'ANDREIA BAFFA', 23, 'SegImob', NULL::text),
    ('TOKIO', 'IMOPRET', 23, 'SegImob', NULL::text),
    ('TOKIO', 'LIBERTY ADM (614835)', 28, 'SegImob', NULL::text),
    ('TOKIO', 'WALKER', 28, 'SegImob', NULL::text),
    ('PORTO FIANÇA', 'ACESSE', 10, 'O2 Seguros', 'ENVIAR TB PELO WPP'),
    ('PORTO FIANÇA', 'ACHARIMOVEIS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ACOM', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ADJENE', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ADJUVE', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ADMINISTRADORA FONTE DE ELIM', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ALEFE', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ALEXANDRE DUHZ', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BACELLAR', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BALCARCE', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BARPEN', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BROTHERHOOD', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BASE', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BCM', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BRASIL IMOVEIS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BSJ', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'CANFIELD', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'CHIEZA (CENTRO JURÍDICO)', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'CARLOS ADOLFO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'CARMO E FLORES', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'CLAUDIA BORGES', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'CHEZ BRASIL', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'CLAUDIA CARVALHO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'CRUZEIRO DO SUL', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'DAHER', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'DANIEL', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'DCS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'DENIS JOSE DE LIMA SOUSA', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'ELIZABETH PINHO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ESTRUTURA', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'EXCLUSIVA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'EXPAN', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ENJOY', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'GAUCHO IMOVEIS', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'GNST', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'GQT', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'HUMBERTO CANALE', 10, 'O2 Seguros', 'financeiro@canaleimoveis.com.br'),
    ('PORTO FIANÇA', 'IMOBARRA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'IMOPRET', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'IMOVEL LIVRE', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'INTEX', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'IURI', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'JGM DE MESQUITA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'LLF (JUST FOR YOU)', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'JIUSTI IMOVEIS', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'JOAO MARTINS SOBRINHO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'LIBERTY ADMINISTRADORA DE BENS LTDA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'LIDER RIO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'LUIS ROMEIRO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'LUMAR', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'LUPE', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'MARCOS CARVALHO IMOVEIS ( CARVALHO IMOVEIS)', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'MARCUS DREHER IMOVEIS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'MARCUS LARANJA DREHER', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'MARISTELA ROCHA DA SILVA', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'METHODUS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'MONTENEGRO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'MVR BARBOSA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'NOVA MORADA | RJ VILLELA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'OBJETIVA', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'PAULA ADRIANA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'PROCED ADM', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'PROCED LOPES', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'R SOARES', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'R046', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'RAFAEL PENNA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'RAMIRO SÁ', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'RAS ADM (EGIDE)', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'RAUL LOPES', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'REAL IMÓVEIS', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'REAL UP', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'RENATO DE SOUSA LOPES', 10, 'O2 Seguros', 'renato@acrj.org.br'),
    ('PORTO FIANÇA', 'RIO CAPITAL', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'RODRIGO NUNES', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'SANDRA XAVIER', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'SCASTTRO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'SENADOR', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'SM IMOVEIS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'SPECIAL', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'SPIN', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'TAGS IMOVEIS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'TERUSZKIN', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'TORRES CINTRA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'TRAVASSOS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'VALVERDE E FERNANDES', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'VIRTHUS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'VIVIAN MANSUR', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'WALKER', 10, 'O2 Seguros', NULL::text),
    ('PORTO RE', 'FLAVIA BECK', 15, 'O2 Seguros', NULL::text),
    ('PORTO RE', 'MARCIA SIMOR PANI', 15, 'O2 Seguros', 'Enviar por wpp também para Great Empire'),
    ('PORTO RE', 'HUMBERTO CANALE', 15, 'O2 Seguros', 'financeiro@canaleimoveis.com.br'),
    ('PORTO RE', 'JOSE CARLOS LOPES', 15, 'O2 Seguros', NULL::text),
    ('PORTO RE', 'KS CONSULTORIA', 15, 'O2 Seguros', NULL::text),
    ('PORTO RE', 'ROBERTO R C FILHO', 15, 'O2 Seguros', NULL::text),
    ('PORTO RE', 'SMART ADM', 15, 'O2 Seguros', NULL::text),
    ('PORTO RE', 'TIAGO SANTOS STORTI', 15, 'O2 Seguros', NULL::text),
    ('PORTO RE', 'SPECIAL', 15, 'O2 Seguros', NULL::text),
    ('TOO', '2MX CONSULTORIA', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'ACERVO CARIOCA', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'ADJUVE', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'ADILSON BRAZ', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'BACELLAR', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'BERGE IMOVEIS', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'BROTHERHOOD', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'CARLOS BECKER', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'CELTHA CONSULTORIA', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'CENTRO JURIDICO', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'CLAUDIA DANTAS', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'DCS', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'EXPAN ADM', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'FRANKLIN RANGEL', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'IMOBILIARIA HUMBERTO CANALE', NULL, 'O2 Seguros', 'financeiro@canaleimoveis.com.br'),
    ('TOO', 'IMOVEL LIVRE', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'INTEX CONSULTORIA', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'IURI CORRETAGEM', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'JGM', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'JOAO MARTINS', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'LLF ASSESSORIA', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'LUCIENE JIUSTI', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'LUMAR ADMINISTRACAO', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'LUPE ADMINISTRACAO', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'MAPA ADM', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'MONTE ALEGRE', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'MONTE ALEGRE GESTAO', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'PAULA ADRIANA', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'PROCED ADM', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'PROCED LOPES', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'R&SA', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'RAMIRO AUGUSTO', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'RIO CAPITAL', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'SANDRA XAVIER', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'SERPA (SPIN)', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'SILVERIO IMOVEIS', NULL, 'O2 Seguros', 'financeiro@silverioimoveis.com.br'),
    ('TOO', 'SPECIAL', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'TIAGO SANTOS', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'VANIA AMARAL', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'WALKER CORRETORA', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'CLEITON ALVES', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'HELIO RIBAS', NULL, 'O2 Capitalização', NULL::text),
    ('POTTENCIAL', 'A. BISBOCCI', 15, NULL::text, 'fabianotrajano@andreata.com.br'),
    ('POTTENCIAL', 'ACERVO CARIOCA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'ACESSE', 15, NULL::text, 'ENVIAR WHATSAPP'),
    ('POTTENCIAL', 'ADJENE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'ADJUVE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'ALEFE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'ALFREDO GUILHERME', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'ANEXO ADM', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'BARPEN', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'BASE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'BERGE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'BROTHERHOOD', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'BSJ', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'CLAUDIA BORGES', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'CANFILD E CANFILD', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'DCS', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'ENJOY', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'ESTRUTURA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'EXCLUSIVA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'HUMBERTO CANALE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'IMOBARRA (VITAL DIAS)', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'IMOVEL LIVRE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'I9', 15, NULL::text, 'ENVIAR WPP TAMBÉM'),
    ('POTTENCIAL', 'JMARTINS', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'JUST FOR YOU (LLF ASSESSORIA)', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'LIDER RIO', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'LSL ASSESORIA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'LUPE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'MAC CONSULTORIA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'MAPA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'MARCUS DREHER', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'METHODUS', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'MONTE ALEGRE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'OBJETIVA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'PAULA ADRIANA (GRÃO PARÁ)', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'PROCED LOPES', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'R&SA GESTAO', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'R046', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'RCJ IMÓVEIS - ROGÉRIO CASSIANO', 15, NULL::text, 'rcjimoveis@gmail.com'),
    ('POTTENCIAL', 'RDJ', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'RAMIRO SA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'SPIN', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'SPECIAL', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'SILVERIO IMOVEIS', 15, NULL::text, 'financeiro@silverioimoveis.com.b'),
    ('POTTENCIAL', 'TORRES CINTRA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'TRAVASSOS E ACHAR IMOVEIS', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'VIZU', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'FERNANDO OLIVEIRA DE PAIVA', 15, NULL::text, 'adm@simplaimobiliaria.com.br'),
    ('YELUM', 'MONTE ALEGRE GESTAO', 10, NULL::text, NULL::text),
    ('YELUM', 'MONTE ALEGRE IMOVEIS', 10, NULL::text, NULL::text),
    ('YELUM', 'LIBERTY CENTRO', 10, NULL::text, NULL::text),
    ('YELUM', 'ESTRUTURA', 15, NULL::text, NULL::text),
    ('YELUM', 'REAL UP', 15, NULL::text, NULL::text),
    ('YELUM', 'SPECIAL RESIDENCE', 15, NULL::text, NULL::text),
    ('YELUM', 'ACESSE', 20, NULL::text, 'enviar por wpp tb'),
    ('YELUM', 'L3', 20, NULL::text, NULL::text),
    ('YELUM', 'PRIVILEGIO', 20, NULL::text, NULL::text)
),
candidatas as (
  select p.seguradora, p.parceiro, p.dia_vencimento, p.origem, p.observacao,
         fe.id as fe_id, coalesce(i.nome, fe.nome_provisorio) as nome_encontrado,
         case when upper(trim(coalesce(i.nome, fe.nome_provisorio))) = upper(trim(p.parceiro)) then 0 else 1 end as prioridade
  from planilha p
  join faturas_esperadas fe on fe.seguradora = p.seguradora
  left join imobiliarias i on i.id = fe.imobiliaria_id
  where
    -- match exato, sem restrição de tamanho
    upper(trim(coalesce(i.nome, fe.nome_provisorio))) = upper(trim(p.parceiro))
    or (
      -- match parcial (contém), só quando os dois nomes têm 4+ caracteres
      length(trim(p.parceiro)) >= 4
      and (
        (fe.imobiliaria_id is not null and length(i.nome) >= 4 and (
          upper(i.nome) like '%' || upper(trim(p.parceiro)) || '%'
          or upper(trim(p.parceiro)) like '%' || upper(i.nome) || '%'
        ))
        or
        (fe.imobiliaria_id is null and length(coalesce(fe.nome_provisorio, '')) >= 4 and (
          upper(coalesce(fe.nome_provisorio, '')) like '%' || upper(trim(p.parceiro)) || '%'
          or upper(trim(p.parceiro)) like '%' || upper(coalesce(fe.nome_provisorio, '')) || '%'
        ))
      )
    )
),
melhor_prioridade as (
  select seguradora, parceiro, min(prioridade) as prioridade
  from candidatas
  group by seguradora, parceiro
),
finalistas as (
  select c.*
  from candidatas c
  join melhor_prioridade mp on mp.seguradora = c.seguradora and mp.parceiro = c.parceiro and mp.prioridade = c.prioridade
),
contagem as (
  select seguradora, parceiro, count(*) as qtd
  from finalistas
  group by seguradora, parceiro
),
unicos as (
  select f.*
  from finalistas f
  join contagem ct on ct.seguradora = f.seguradora and ct.parceiro = f.parceiro and ct.qtd = 1
)
update faturas_esperadas fe
set dia_vencimento = coalesce(u.dia_vencimento, fe.dia_vencimento),
    cnpj_o2 = coalesce(u.origem, fe.cnpj_o2),
    observacao = coalesce(u.observacao, fe.observacao),
    ativo = true
from unicos u
where fe.id = u.fe_id;

-- Diagnóstico 1: sem candidato nenhum -- deve ter caído bastante em relação
-- à v5 (22 antes; os de 3 letras devem ter sumido).
with planilha (seguradora, parceiro, dia_vencimento, origem, observacao) as (
  values
    ('TOKIO', 'PROMOVEL IMOBILIÁRIA LTDA', 8, 'SegImob', 'locacao@imoveisponto.com.br'),
    ('TOKIO', 'BERGE', 9, 'SegImob', NULL::text),
    ('TOKIO', 'DAHER', 9, 'SegImob', NULL::text),
    ('TOKIO', 'RIO CAPITAL', 9, 'SegImob', NULL::text),
    ('TOKIO', 'PROCED LOPES', 10, 'SegImob', NULL::text),
    ('TOKIO', 'ACERVO CARIOCA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'ACESSE IMÓVEL RJ', 15, 'SegImob', 'ENVIAR WPP TAMBÉM'),
    ('TOKIO', 'ADILSON BRAZ', 15, 'SegImob', NULL::text),
    ('TOKIO', 'ADJUVE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'André gomes dos santos', 15, 'SegImob', 'andrerjgomes@gmail.com'),
    ('TOKIO', 'ALBERTO SOARES', 15, 'SegImob', NULL::text),
    ('TOKIO', 'ALEXANDRE CARNEIRO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'ALEXANDRE DUHZ', 15, 'SegImob', NULL::text),
    ('TOKIO', 'AMARANTE E GANDARA', 15, 'O2 Seguros', NULL::text),
    ('TOKIO', 'ANA CARLA ROSSI REZENDE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'BACELLAR', 15, 'SegImob', NULL::text),
    ('TOKIO', 'BALCARCE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'BASE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'BCM', 15, 'SegImob', NULL::text),
    ('TOKIO', 'BROTHERHOOD', 15, 'SegImob', NULL::text),
    ('TOKIO', 'BS MACHADO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'CARLOS ADOLFO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'CASA CAPRI', 15, 'SegImob', NULL::text),
    ('TOKIO', 'CENTRO JURIDICO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'CLAUDIA CARVALHO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'CRISTIANO ALVES', 15, 'SegImob', NULL::text),
    ('TOKIO', 'CHEZ BRASIL', 15, 'SegImob', NULL::text),
    ('TOKIO', 'DOMENICI', 15, 'SegImob', NULL::text),
    ('TOKIO', 'DCS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'EXCLUSIVA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'ENJOY', 15, 'SegImob', NULL::text),
    ('TOKIO', 'FLAVIO BRAGA MONTEIRO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'FR COSTA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'GAUCHO IMOVEIS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'GRACE GONCALVES', 15, 'SegImob', NULL::text),
    ('TOKIO', 'HUMBERTO CANALE', 15, 'SegImob', 'financeiro@canaleimoveis.com.br'),
    ('TOKIO', 'HÉLIO HIBAS (HC CONSULTORIA)', 15, 'SegImob', NULL::text),
    ('TOKIO', 'IMOBARRA (VITAL DIAS)', 15, 'SegImob', NULL::text),
    ('TOKIO', 'IMOVEL LIVRE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'IMOVELUM PLATAFORMA IMOBILIARIA LTDA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'I9 INOVE', 15, 'SegImob', 'ENVIAR WPP TAMBÉM gestao@inovesolucoescontabeis.com.br'),
    ('TOKIO', 'JIUSTI IMOVEIS CONDOMINIOS', 15, 'O2 Seguros', NULL::text),
    ('TOKIO', 'JOAO MARCO BESSA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'JOAO MARTINS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'JSJ', 15, 'SegImob', NULL::text),
    ('TOKIO', 'VERITAS IMOVEIS SOLUÇÕES', 15, 'SegImob', 'amitrano78@gmail.com'),
    ('TOKIO', 'LAGORIO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'LIBERTY ADM (722805)', 15, 'SegImob', NULL::text),
    ('TOKIO', 'LIVE IMOVEIS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'LÍDER RIO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'LOURENCO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'LUIS ROMEIRO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'LUIZ FLAVIO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'M V R', 15, 'SegImob', NULL::text),
    ('TOKIO', 'MAPA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'MARREIROS IMOVEIS', 15, 'SegImob', 'imoveismarreiros@gmail.com'),
    ('TOKIO', 'MATERDRADE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'MAX BROKERS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'METHODUS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'MONTE ALEGRE EMPREENDIMENTOS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'MONTE ALEGRE GESTÃO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'MONTENEGRO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'MORAES E VECCHI', 15, 'SegImob', NULL::text),
    ('TOKIO', 'NELIO GOMES', 15, 'SegImob', NULL::text),
    ('TOKIO', 'OBJETIVA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'OKRE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'PAULO SAMPAIO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'PINTAS IMOVEIS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'R N P FORMOSO CORRETAGEM', 15, 'SegImob', NULL::text),
    ('TOKIO', 'SPECIAL RESIDENCE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'R&SA GESTÃO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'RCJ (ROGERIO CASSIANO)', 15, 'SegImob', NULL::text),
    ('TOKIO', 'RDJ', 15, 'SegImob', NULL::text),
    ('TOKIO', 'REAL UP', 15, 'SegImob', NULL::text),
    ('TOKIO', 'RHIAN AZEREDO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'RIBAS HP', 15, 'O2 Seguros', NULL::text),
    ('TOKIO', 'RJ VILLELA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'RODRIGO ARRUDA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'R SOARES', 15, 'SegImob', 'guiporcaro@hotmail.com'),
    ('TOKIO', 'SCASTTRO IMOVEIS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'SELLING', 15, 'SegImob', NULL::text),
    ('TOKIO', 'SELMA MARIA CARDOSO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'SM ADM', 15, 'SegImob', NULL::text),
    ('TOKIO', 'SPIN', 15, 'SegImob', NULL::text),
    ('TOKIO', 'SUA CASA DIGITAL', 15, 'SegImob', NULL::text),
    ('TOKIO', 'TAGS IMOVEIS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'TRATTO IMOVEIS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'TRAVASSOS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'SERRA REAL', 15, 'SegImob', 'Serrarealimoveis@gmail.com'),
    ('TOKIO', 'TWP', 15, 'SegImob', NULL::text),
    ('TOKIO', 'VÂNIA AMARAL', 15, 'SegImob', NULL::text),
    ('TOKIO', 'VENDABLE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'VIVIAN MANSUR', 15, 'SegImob', 'Enviar pelo wpp também a partir de nov/25'),
    ('TOKIO', 'MTT 100', 17, 'SegImob', NULL::text),
    ('TOKIO', 'MTT 300', 17, 'SegImob', NULL::text),
    ('TOKIO', 'MTT 500', 17, 'SegImob', NULL::text),
    ('TOKIO', 'MTT 600', 17, 'SegImob', NULL::text),
    ('TOKIO', 'ADAK', 20, 'SegImob', NULL::text),
    ('TOKIO', 'NATELMA', 20, 'O2 Seguros', NULL::text),
    ('TOKIO', 'PAULA ADRIANA', 20, 'SegImob', NULL::text),
    ('TOKIO', 'RAFAEL PENNA', 20, 'SegImob', NULL::text),
    ('TOKIO', 'TDC', 20, 'O2 Seguros', NULL::text),
    ('TOKIO', 'VALVERDE E FERNANDES', 20, 'SegImob', NULL::text),
    ('TOKIO', 'BSJ', 21, 'SegImob', NULL::text),
    ('TOKIO', 'MICHELE FREITAS', 22, 'O2 Seguros', NULL::text),
    ('TOKIO', 'ACVM', 23, 'SegImob', NULL::text),
    ('TOKIO', 'SILVÉRIO IMÓVEIS', 23, 'SegImob', 'financeiro@silverioimoveis.com.br'),
    ('TOKIO', 'ANDREIA BAFFA', 23, 'SegImob', NULL::text),
    ('TOKIO', 'IMOPRET', 23, 'SegImob', NULL::text),
    ('TOKIO', 'LIBERTY ADM (614835)', 28, 'SegImob', NULL::text),
    ('TOKIO', 'WALKER', 28, 'SegImob', NULL::text),
    ('PORTO FIANÇA', 'ACESSE', 10, 'O2 Seguros', 'ENVIAR TB PELO WPP'),
    ('PORTO FIANÇA', 'ACHARIMOVEIS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ACOM', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ADJENE', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ADJUVE', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ADMINISTRADORA FONTE DE ELIM', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ALEFE', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ALEXANDRE DUHZ', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BACELLAR', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BALCARCE', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BARPEN', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BROTHERHOOD', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BASE', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BCM', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BRASIL IMOVEIS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BSJ', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'CANFIELD', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'CHIEZA (CENTRO JURÍDICO)', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'CARLOS ADOLFO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'CARMO E FLORES', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'CLAUDIA BORGES', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'CHEZ BRASIL', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'CLAUDIA CARVALHO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'CRUZEIRO DO SUL', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'DAHER', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'DANIEL', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'DCS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'DENIS JOSE DE LIMA SOUSA', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'ELIZABETH PINHO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ESTRUTURA', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'EXCLUSIVA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'EXPAN', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ENJOY', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'GAUCHO IMOVEIS', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'GNST', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'GQT', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'HUMBERTO CANALE', 10, 'O2 Seguros', 'financeiro@canaleimoveis.com.br'),
    ('PORTO FIANÇA', 'IMOBARRA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'IMOPRET', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'IMOVEL LIVRE', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'INTEX', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'IURI', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'JGM DE MESQUITA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'LLF (JUST FOR YOU)', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'JIUSTI IMOVEIS', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'JOAO MARTINS SOBRINHO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'LIBERTY ADMINISTRADORA DE BENS LTDA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'LIDER RIO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'LUIS ROMEIRO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'LUMAR', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'LUPE', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'MARCOS CARVALHO IMOVEIS ( CARVALHO IMOVEIS)', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'MARCUS DREHER IMOVEIS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'MARCUS LARANJA DREHER', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'MARISTELA ROCHA DA SILVA', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'METHODUS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'MONTENEGRO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'MVR BARBOSA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'NOVA MORADA | RJ VILLELA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'OBJETIVA', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'PAULA ADRIANA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'PROCED ADM', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'PROCED LOPES', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'R SOARES', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'R046', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'RAFAEL PENNA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'RAMIRO SÁ', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'RAS ADM (EGIDE)', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'RAUL LOPES', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'REAL IMÓVEIS', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'REAL UP', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'RENATO DE SOUSA LOPES', 10, 'O2 Seguros', 'renato@acrj.org.br'),
    ('PORTO FIANÇA', 'RIO CAPITAL', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'RODRIGO NUNES', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'SANDRA XAVIER', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'SCASTTRO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'SENADOR', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'SM IMOVEIS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'SPECIAL', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'SPIN', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'TAGS IMOVEIS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'TERUSZKIN', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'TORRES CINTRA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'TRAVASSOS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'VALVERDE E FERNANDES', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'VIRTHUS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'VIVIAN MANSUR', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'WALKER', 10, 'O2 Seguros', NULL::text),
    ('PORTO RE', 'FLAVIA BECK', 15, 'O2 Seguros', NULL::text),
    ('PORTO RE', 'MARCIA SIMOR PANI', 15, 'O2 Seguros', 'Enviar por wpp também para Great Empire'),
    ('PORTO RE', 'HUMBERTO CANALE', 15, 'O2 Seguros', 'financeiro@canaleimoveis.com.br'),
    ('PORTO RE', 'JOSE CARLOS LOPES', 15, 'O2 Seguros', NULL::text),
    ('PORTO RE', 'KS CONSULTORIA', 15, 'O2 Seguros', NULL::text),
    ('PORTO RE', 'ROBERTO R C FILHO', 15, 'O2 Seguros', NULL::text),
    ('PORTO RE', 'SMART ADM', 15, 'O2 Seguros', NULL::text),
    ('PORTO RE', 'TIAGO SANTOS STORTI', 15, 'O2 Seguros', NULL::text),
    ('PORTO RE', 'SPECIAL', 15, 'O2 Seguros', NULL::text),
    ('TOO', '2MX CONSULTORIA', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'ACERVO CARIOCA', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'ADJUVE', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'ADILSON BRAZ', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'BACELLAR', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'BERGE IMOVEIS', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'BROTHERHOOD', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'CARLOS BECKER', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'CELTHA CONSULTORIA', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'CENTRO JURIDICO', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'CLAUDIA DANTAS', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'DCS', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'EXPAN ADM', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'FRANKLIN RANGEL', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'IMOBILIARIA HUMBERTO CANALE', NULL, 'O2 Seguros', 'financeiro@canaleimoveis.com.br'),
    ('TOO', 'IMOVEL LIVRE', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'INTEX CONSULTORIA', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'IURI CORRETAGEM', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'JGM', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'JOAO MARTINS', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'LLF ASSESSORIA', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'LUCIENE JIUSTI', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'LUMAR ADMINISTRACAO', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'LUPE ADMINISTRACAO', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'MAPA ADM', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'MONTE ALEGRE', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'MONTE ALEGRE GESTAO', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'PAULA ADRIANA', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'PROCED ADM', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'PROCED LOPES', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'R&SA', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'RAMIRO AUGUSTO', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'RIO CAPITAL', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'SANDRA XAVIER', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'SERPA (SPIN)', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'SILVERIO IMOVEIS', NULL, 'O2 Seguros', 'financeiro@silverioimoveis.com.br'),
    ('TOO', 'SPECIAL', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'TIAGO SANTOS', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'VANIA AMARAL', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'WALKER CORRETORA', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'CLEITON ALVES', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'HELIO RIBAS', NULL, 'O2 Capitalização', NULL::text),
    ('POTTENCIAL', 'A. BISBOCCI', 15, NULL::text, 'fabianotrajano@andreata.com.br'),
    ('POTTENCIAL', 'ACERVO CARIOCA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'ACESSE', 15, NULL::text, 'ENVIAR WHATSAPP'),
    ('POTTENCIAL', 'ADJENE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'ADJUVE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'ALEFE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'ALFREDO GUILHERME', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'ANEXO ADM', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'BARPEN', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'BASE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'BERGE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'BROTHERHOOD', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'BSJ', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'CLAUDIA BORGES', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'CANFILD E CANFILD', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'DCS', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'ENJOY', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'ESTRUTURA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'EXCLUSIVA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'HUMBERTO CANALE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'IMOBARRA (VITAL DIAS)', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'IMOVEL LIVRE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'I9', 15, NULL::text, 'ENVIAR WPP TAMBÉM'),
    ('POTTENCIAL', 'JMARTINS', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'JUST FOR YOU (LLF ASSESSORIA)', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'LIDER RIO', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'LSL ASSESORIA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'LUPE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'MAC CONSULTORIA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'MAPA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'MARCUS DREHER', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'METHODUS', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'MONTE ALEGRE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'OBJETIVA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'PAULA ADRIANA (GRÃO PARÁ)', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'PROCED LOPES', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'R&SA GESTAO', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'R046', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'RCJ IMÓVEIS - ROGÉRIO CASSIANO', 15, NULL::text, 'rcjimoveis@gmail.com'),
    ('POTTENCIAL', 'RDJ', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'RAMIRO SA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'SPIN', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'SPECIAL', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'SILVERIO IMOVEIS', 15, NULL::text, 'financeiro@silverioimoveis.com.b'),
    ('POTTENCIAL', 'TORRES CINTRA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'TRAVASSOS E ACHAR IMOVEIS', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'VIZU', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'FERNANDO OLIVEIRA DE PAIVA', 15, NULL::text, 'adm@simplaimobiliaria.com.br'),
    ('YELUM', 'MONTE ALEGRE GESTAO', 10, NULL::text, NULL::text),
    ('YELUM', 'MONTE ALEGRE IMOVEIS', 10, NULL::text, NULL::text),
    ('YELUM', 'LIBERTY CENTRO', 10, NULL::text, NULL::text),
    ('YELUM', 'ESTRUTURA', 15, NULL::text, NULL::text),
    ('YELUM', 'REAL UP', 15, NULL::text, NULL::text),
    ('YELUM', 'SPECIAL RESIDENCE', 15, NULL::text, NULL::text),
    ('YELUM', 'ACESSE', 20, NULL::text, 'enviar por wpp tb'),
    ('YELUM', 'L3', 20, NULL::text, NULL::text),
    ('YELUM', 'PRIVILEGIO', 20, NULL::text, NULL::text)
)
select p.seguradora, p.parceiro
from planilha p
where not exists (
  select 1 from faturas_esperadas fe
  left join imobiliarias i on i.id = fe.imobiliaria_id
  where fe.seguradora = p.seguradora
    and (
      upper(trim(coalesce(i.nome, fe.nome_provisorio))) = upper(trim(p.parceiro))
      or (
        length(trim(p.parceiro)) >= 4
        and (
          (fe.imobiliaria_id is not null and length(i.nome) >= 4 and (
            upper(i.nome) like '%' || upper(trim(p.parceiro)) || '%'
            or upper(trim(p.parceiro)) like '%' || upper(i.nome) || '%'
          ))
          or
          (fe.imobiliaria_id is null and length(coalesce(fe.nome_provisorio, '')) >= 4 and (
            upper(coalesce(fe.nome_provisorio, '')) like '%' || upper(trim(p.parceiro)) || '%'
            or upper(trim(p.parceiro)) like '%' || upper(coalesce(fe.nome_provisorio, '')) || '%'
          ))
        )
      )
    )
)
order by p.seguradora, p.parceiro;

-- Diagnóstico 2: ainda ambíguo depois da prioridade por match exato.
with planilha (seguradora, parceiro, dia_vencimento, origem, observacao) as (
  values
    ('TOKIO', 'PROMOVEL IMOBILIÁRIA LTDA', 8, 'SegImob', 'locacao@imoveisponto.com.br'),
    ('TOKIO', 'BERGE', 9, 'SegImob', NULL::text),
    ('TOKIO', 'DAHER', 9, 'SegImob', NULL::text),
    ('TOKIO', 'RIO CAPITAL', 9, 'SegImob', NULL::text),
    ('TOKIO', 'PROCED LOPES', 10, 'SegImob', NULL::text),
    ('TOKIO', 'ACERVO CARIOCA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'ACESSE IMÓVEL RJ', 15, 'SegImob', 'ENVIAR WPP TAMBÉM'),
    ('TOKIO', 'ADILSON BRAZ', 15, 'SegImob', NULL::text),
    ('TOKIO', 'ADJUVE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'André gomes dos santos', 15, 'SegImob', 'andrerjgomes@gmail.com'),
    ('TOKIO', 'ALBERTO SOARES', 15, 'SegImob', NULL::text),
    ('TOKIO', 'ALEXANDRE CARNEIRO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'ALEXANDRE DUHZ', 15, 'SegImob', NULL::text),
    ('TOKIO', 'AMARANTE E GANDARA', 15, 'O2 Seguros', NULL::text),
    ('TOKIO', 'ANA CARLA ROSSI REZENDE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'BACELLAR', 15, 'SegImob', NULL::text),
    ('TOKIO', 'BALCARCE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'BASE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'BCM', 15, 'SegImob', NULL::text),
    ('TOKIO', 'BROTHERHOOD', 15, 'SegImob', NULL::text),
    ('TOKIO', 'BS MACHADO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'CARLOS ADOLFO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'CASA CAPRI', 15, 'SegImob', NULL::text),
    ('TOKIO', 'CENTRO JURIDICO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'CLAUDIA CARVALHO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'CRISTIANO ALVES', 15, 'SegImob', NULL::text),
    ('TOKIO', 'CHEZ BRASIL', 15, 'SegImob', NULL::text),
    ('TOKIO', 'DOMENICI', 15, 'SegImob', NULL::text),
    ('TOKIO', 'DCS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'EXCLUSIVA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'ENJOY', 15, 'SegImob', NULL::text),
    ('TOKIO', 'FLAVIO BRAGA MONTEIRO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'FR COSTA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'GAUCHO IMOVEIS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'GRACE GONCALVES', 15, 'SegImob', NULL::text),
    ('TOKIO', 'HUMBERTO CANALE', 15, 'SegImob', 'financeiro@canaleimoveis.com.br'),
    ('TOKIO', 'HÉLIO HIBAS (HC CONSULTORIA)', 15, 'SegImob', NULL::text),
    ('TOKIO', 'IMOBARRA (VITAL DIAS)', 15, 'SegImob', NULL::text),
    ('TOKIO', 'IMOVEL LIVRE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'IMOVELUM PLATAFORMA IMOBILIARIA LTDA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'I9 INOVE', 15, 'SegImob', 'ENVIAR WPP TAMBÉM gestao@inovesolucoescontabeis.com.br'),
    ('TOKIO', 'JIUSTI IMOVEIS CONDOMINIOS', 15, 'O2 Seguros', NULL::text),
    ('TOKIO', 'JOAO MARCO BESSA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'JOAO MARTINS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'JSJ', 15, 'SegImob', NULL::text),
    ('TOKIO', 'VERITAS IMOVEIS SOLUÇÕES', 15, 'SegImob', 'amitrano78@gmail.com'),
    ('TOKIO', 'LAGORIO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'LIBERTY ADM (722805)', 15, 'SegImob', NULL::text),
    ('TOKIO', 'LIVE IMOVEIS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'LÍDER RIO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'LOURENCO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'LUIS ROMEIRO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'LUIZ FLAVIO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'M V R', 15, 'SegImob', NULL::text),
    ('TOKIO', 'MAPA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'MARREIROS IMOVEIS', 15, 'SegImob', 'imoveismarreiros@gmail.com'),
    ('TOKIO', 'MATERDRADE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'MAX BROKERS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'METHODUS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'MONTE ALEGRE EMPREENDIMENTOS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'MONTE ALEGRE GESTÃO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'MONTENEGRO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'MORAES E VECCHI', 15, 'SegImob', NULL::text),
    ('TOKIO', 'NELIO GOMES', 15, 'SegImob', NULL::text),
    ('TOKIO', 'OBJETIVA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'OKRE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'PAULO SAMPAIO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'PINTAS IMOVEIS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'R N P FORMOSO CORRETAGEM', 15, 'SegImob', NULL::text),
    ('TOKIO', 'SPECIAL RESIDENCE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'R&SA GESTÃO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'RCJ (ROGERIO CASSIANO)', 15, 'SegImob', NULL::text),
    ('TOKIO', 'RDJ', 15, 'SegImob', NULL::text),
    ('TOKIO', 'REAL UP', 15, 'SegImob', NULL::text),
    ('TOKIO', 'RHIAN AZEREDO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'RIBAS HP', 15, 'O2 Seguros', NULL::text),
    ('TOKIO', 'RJ VILLELA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'RODRIGO ARRUDA', 15, 'SegImob', NULL::text),
    ('TOKIO', 'R SOARES', 15, 'SegImob', 'guiporcaro@hotmail.com'),
    ('TOKIO', 'SCASTTRO IMOVEIS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'SELLING', 15, 'SegImob', NULL::text),
    ('TOKIO', 'SELMA MARIA CARDOSO', 15, 'SegImob', NULL::text),
    ('TOKIO', 'SM ADM', 15, 'SegImob', NULL::text),
    ('TOKIO', 'SPIN', 15, 'SegImob', NULL::text),
    ('TOKIO', 'SUA CASA DIGITAL', 15, 'SegImob', NULL::text),
    ('TOKIO', 'TAGS IMOVEIS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'TRATTO IMOVEIS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'TRAVASSOS', 15, 'SegImob', NULL::text),
    ('TOKIO', 'SERRA REAL', 15, 'SegImob', 'Serrarealimoveis@gmail.com'),
    ('TOKIO', 'TWP', 15, 'SegImob', NULL::text),
    ('TOKIO', 'VÂNIA AMARAL', 15, 'SegImob', NULL::text),
    ('TOKIO', 'VENDABLE', 15, 'SegImob', NULL::text),
    ('TOKIO', 'VIVIAN MANSUR', 15, 'SegImob', 'Enviar pelo wpp também a partir de nov/25'),
    ('TOKIO', 'MTT 100', 17, 'SegImob', NULL::text),
    ('TOKIO', 'MTT 300', 17, 'SegImob', NULL::text),
    ('TOKIO', 'MTT 500', 17, 'SegImob', NULL::text),
    ('TOKIO', 'MTT 600', 17, 'SegImob', NULL::text),
    ('TOKIO', 'ADAK', 20, 'SegImob', NULL::text),
    ('TOKIO', 'NATELMA', 20, 'O2 Seguros', NULL::text),
    ('TOKIO', 'PAULA ADRIANA', 20, 'SegImob', NULL::text),
    ('TOKIO', 'RAFAEL PENNA', 20, 'SegImob', NULL::text),
    ('TOKIO', 'TDC', 20, 'O2 Seguros', NULL::text),
    ('TOKIO', 'VALVERDE E FERNANDES', 20, 'SegImob', NULL::text),
    ('TOKIO', 'BSJ', 21, 'SegImob', NULL::text),
    ('TOKIO', 'MICHELE FREITAS', 22, 'O2 Seguros', NULL::text),
    ('TOKIO', 'ACVM', 23, 'SegImob', NULL::text),
    ('TOKIO', 'SILVÉRIO IMÓVEIS', 23, 'SegImob', 'financeiro@silverioimoveis.com.br'),
    ('TOKIO', 'ANDREIA BAFFA', 23, 'SegImob', NULL::text),
    ('TOKIO', 'IMOPRET', 23, 'SegImob', NULL::text),
    ('TOKIO', 'LIBERTY ADM (614835)', 28, 'SegImob', NULL::text),
    ('TOKIO', 'WALKER', 28, 'SegImob', NULL::text),
    ('PORTO FIANÇA', 'ACESSE', 10, 'O2 Seguros', 'ENVIAR TB PELO WPP'),
    ('PORTO FIANÇA', 'ACHARIMOVEIS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ACOM', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ADJENE', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ADJUVE', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ADMINISTRADORA FONTE DE ELIM', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ALEFE', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ALEXANDRE DUHZ', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BACELLAR', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BALCARCE', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BARPEN', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BROTHERHOOD', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BASE', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BCM', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BRASIL IMOVEIS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'BSJ', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'CANFIELD', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'CHIEZA (CENTRO JURÍDICO)', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'CARLOS ADOLFO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'CARMO E FLORES', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'CLAUDIA BORGES', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'CHEZ BRASIL', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'CLAUDIA CARVALHO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'CRUZEIRO DO SUL', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'DAHER', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'DANIEL', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'DCS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'DENIS JOSE DE LIMA SOUSA', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'ELIZABETH PINHO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ESTRUTURA', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'EXCLUSIVA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'EXPAN', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'ENJOY', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'GAUCHO IMOVEIS', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'GNST', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'GQT', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'HUMBERTO CANALE', 10, 'O2 Seguros', 'financeiro@canaleimoveis.com.br'),
    ('PORTO FIANÇA', 'IMOBARRA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'IMOPRET', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'IMOVEL LIVRE', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'INTEX', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'IURI', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'JGM DE MESQUITA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'LLF (JUST FOR YOU)', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'JIUSTI IMOVEIS', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'JOAO MARTINS SOBRINHO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'LIBERTY ADMINISTRADORA DE BENS LTDA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'LIDER RIO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'LUIS ROMEIRO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'LUMAR', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'LUPE', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'MARCOS CARVALHO IMOVEIS ( CARVALHO IMOVEIS)', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'MARCUS DREHER IMOVEIS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'MARCUS LARANJA DREHER', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'MARISTELA ROCHA DA SILVA', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'METHODUS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'MONTENEGRO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'MVR BARBOSA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'NOVA MORADA | RJ VILLELA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'OBJETIVA', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'PAULA ADRIANA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'PROCED ADM', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'PROCED LOPES', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'R SOARES', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'R046', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'RAFAEL PENNA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'RAMIRO SÁ', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'RAS ADM (EGIDE)', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'RAUL LOPES', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'REAL IMÓVEIS', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'REAL UP', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'RENATO DE SOUSA LOPES', 10, 'O2 Seguros', 'renato@acrj.org.br'),
    ('PORTO FIANÇA', 'RIO CAPITAL', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'RODRIGO NUNES', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'SANDRA XAVIER', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'SCASTTRO', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'SENADOR', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'SM IMOVEIS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'SPECIAL', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'SPIN', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'TAGS IMOVEIS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'TERUSZKIN', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'TORRES CINTRA', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'TRAVASSOS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'VALVERDE E FERNANDES', 10, 'O2 Capitalização', NULL::text),
    ('PORTO FIANÇA', 'VIRTHUS', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'VIVIAN MANSUR', 10, 'O2 Seguros', NULL::text),
    ('PORTO FIANÇA', 'WALKER', 10, 'O2 Seguros', NULL::text),
    ('PORTO RE', 'FLAVIA BECK', 15, 'O2 Seguros', NULL::text),
    ('PORTO RE', 'MARCIA SIMOR PANI', 15, 'O2 Seguros', 'Enviar por wpp também para Great Empire'),
    ('PORTO RE', 'HUMBERTO CANALE', 15, 'O2 Seguros', 'financeiro@canaleimoveis.com.br'),
    ('PORTO RE', 'JOSE CARLOS LOPES', 15, 'O2 Seguros', NULL::text),
    ('PORTO RE', 'KS CONSULTORIA', 15, 'O2 Seguros', NULL::text),
    ('PORTO RE', 'ROBERTO R C FILHO', 15, 'O2 Seguros', NULL::text),
    ('PORTO RE', 'SMART ADM', 15, 'O2 Seguros', NULL::text),
    ('PORTO RE', 'TIAGO SANTOS STORTI', 15, 'O2 Seguros', NULL::text),
    ('PORTO RE', 'SPECIAL', 15, 'O2 Seguros', NULL::text),
    ('TOO', '2MX CONSULTORIA', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'ACERVO CARIOCA', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'ADJUVE', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'ADILSON BRAZ', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'BACELLAR', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'BERGE IMOVEIS', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'BROTHERHOOD', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'CARLOS BECKER', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'CELTHA CONSULTORIA', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'CENTRO JURIDICO', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'CLAUDIA DANTAS', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'DCS', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'EXPAN ADM', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'FRANKLIN RANGEL', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'IMOBILIARIA HUMBERTO CANALE', NULL, 'O2 Seguros', 'financeiro@canaleimoveis.com.br'),
    ('TOO', 'IMOVEL LIVRE', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'INTEX CONSULTORIA', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'IURI CORRETAGEM', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'JGM', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'JOAO MARTINS', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'LLF ASSESSORIA', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'LUCIENE JIUSTI', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'LUMAR ADMINISTRACAO', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'LUPE ADMINISTRACAO', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'MAPA ADM', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'MONTE ALEGRE', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'MONTE ALEGRE GESTAO', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'PAULA ADRIANA', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'PROCED ADM', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'PROCED LOPES', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'R&SA', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'RAMIRO AUGUSTO', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'RIO CAPITAL', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'SANDRA XAVIER', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'SERPA (SPIN)', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'SILVERIO IMOVEIS', NULL, 'O2 Seguros', 'financeiro@silverioimoveis.com.br'),
    ('TOO', 'SPECIAL', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'TIAGO SANTOS', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'VANIA AMARAL', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'WALKER CORRETORA', NULL, 'O2 Capitalização', NULL::text),
    ('TOO', 'CLEITON ALVES', NULL, 'O2 Seguros', NULL::text),
    ('TOO', 'HELIO RIBAS', NULL, 'O2 Capitalização', NULL::text),
    ('POTTENCIAL', 'A. BISBOCCI', 15, NULL::text, 'fabianotrajano@andreata.com.br'),
    ('POTTENCIAL', 'ACERVO CARIOCA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'ACESSE', 15, NULL::text, 'ENVIAR WHATSAPP'),
    ('POTTENCIAL', 'ADJENE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'ADJUVE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'ALEFE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'ALFREDO GUILHERME', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'ANEXO ADM', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'BARPEN', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'BASE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'BERGE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'BROTHERHOOD', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'BSJ', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'CLAUDIA BORGES', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'CANFILD E CANFILD', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'DCS', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'ENJOY', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'ESTRUTURA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'EXCLUSIVA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'HUMBERTO CANALE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'IMOBARRA (VITAL DIAS)', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'IMOVEL LIVRE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'I9', 15, NULL::text, 'ENVIAR WPP TAMBÉM'),
    ('POTTENCIAL', 'JMARTINS', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'JUST FOR YOU (LLF ASSESSORIA)', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'LIDER RIO', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'LSL ASSESORIA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'LUPE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'MAC CONSULTORIA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'MAPA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'MARCUS DREHER', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'METHODUS', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'MONTE ALEGRE', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'OBJETIVA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'PAULA ADRIANA (GRÃO PARÁ)', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'PROCED LOPES', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'R&SA GESTAO', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'R046', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'RCJ IMÓVEIS - ROGÉRIO CASSIANO', 15, NULL::text, 'rcjimoveis@gmail.com'),
    ('POTTENCIAL', 'RDJ', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'RAMIRO SA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'SPIN', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'SPECIAL', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'SILVERIO IMOVEIS', 15, NULL::text, 'financeiro@silverioimoveis.com.b'),
    ('POTTENCIAL', 'TORRES CINTRA', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'TRAVASSOS E ACHAR IMOVEIS', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'VIZU', 15, NULL::text, NULL::text),
    ('POTTENCIAL', 'FERNANDO OLIVEIRA DE PAIVA', 15, NULL::text, 'adm@simplaimobiliaria.com.br'),
    ('YELUM', 'MONTE ALEGRE GESTAO', 10, NULL::text, NULL::text),
    ('YELUM', 'MONTE ALEGRE IMOVEIS', 10, NULL::text, NULL::text),
    ('YELUM', 'LIBERTY CENTRO', 10, NULL::text, NULL::text),
    ('YELUM', 'ESTRUTURA', 15, NULL::text, NULL::text),
    ('YELUM', 'REAL UP', 15, NULL::text, NULL::text),
    ('YELUM', 'SPECIAL RESIDENCE', 15, NULL::text, NULL::text),
    ('YELUM', 'ACESSE', 20, NULL::text, 'enviar por wpp tb'),
    ('YELUM', 'L3', 20, NULL::text, NULL::text),
    ('YELUM', 'PRIVILEGIO', 20, NULL::text, NULL::text)
),
candidatas as (
  select p.seguradora, p.parceiro, p.dia_vencimento, p.origem, p.observacao,
         fe.id as fe_id, coalesce(i.nome, fe.nome_provisorio) as nome_encontrado,
         case when upper(trim(coalesce(i.nome, fe.nome_provisorio))) = upper(trim(p.parceiro)) then 0 else 1 end as prioridade
  from planilha p
  join faturas_esperadas fe on fe.seguradora = p.seguradora
  left join imobiliarias i on i.id = fe.imobiliaria_id
  where
    -- match exato, sem restrição de tamanho
    upper(trim(coalesce(i.nome, fe.nome_provisorio))) = upper(trim(p.parceiro))
    or (
      -- match parcial (contém), só quando os dois nomes têm 4+ caracteres
      length(trim(p.parceiro)) >= 4
      and (
        (fe.imobiliaria_id is not null and length(i.nome) >= 4 and (
          upper(i.nome) like '%' || upper(trim(p.parceiro)) || '%'
          or upper(trim(p.parceiro)) like '%' || upper(i.nome) || '%'
        ))
        or
        (fe.imobiliaria_id is null and length(coalesce(fe.nome_provisorio, '')) >= 4 and (
          upper(coalesce(fe.nome_provisorio, '')) like '%' || upper(trim(p.parceiro)) || '%'
          or upper(trim(p.parceiro)) like '%' || upper(coalesce(fe.nome_provisorio, '')) || '%'
        ))
      )
    )
),
melhor_prioridade as (
  select seguradora, parceiro, min(prioridade) as prioridade
  from candidatas
  group by seguradora, parceiro
),
finalistas as (
  select c.*
  from candidatas c
  join melhor_prioridade mp on mp.seguradora = c.seguradora and mp.parceiro = c.parceiro and mp.prioridade = c.prioridade
)
select seguradora, parceiro, array_agg(distinct nome_encontrado) as candidatos
from finalistas
group by seguradora, parceiro
having count(distinct nome_encontrado) > 1
order by seguradora, parceiro;
