-- Lista dos 113 nomes esperados na Tokio (planilha original) -- acha
-- qual linha ATUAL não corresponde a nenhum deles (nem por igualdade, nem
-- por conteúdo).
with esperado (parceiro) as (
  values
    ('PROMOVEL IMOBILIÁRIA LTDA'),
    ('BERGE'),
    ('DAHER'),
    ('RIO CAPITAL'),
    ('PROCED LOPES'),
    ('ACERVO CARIOCA'),
    ('ACESSE IMÓVEL RJ'),
    ('ADILSON BRAZ'),
    ('ADJUVE'),
    ('André gomes dos santos'),
    ('ALBERTO SOARES'),
    ('ALEXANDRE CARNEIRO'),
    ('ALEXANDRE DUHZ'),
    ('AMARANTE E GANDARA'),
    ('ANA CARLA ROSSI REZENDE'),
    ('BACELLAR'),
    ('BALCARCE'),
    ('BASE'),
    ('BCM'),
    ('BROTHERHOOD'),
    ('BS MACHADO'),
    ('CARLOS ADOLFO'),
    ('CASA CAPRI'),
    ('CENTRO JURIDICO'),
    ('CLAUDIA CARVALHO'),
    ('CRISTIANO ALVES'),
    ('CHEZ BRASIL'),
    ('DOMENICI'),
    ('DCS'),
    ('EXCLUSIVA'),
    ('ENJOY'),
    ('EXPAN'),
    ('FLAVIO BRAGA MONTEIRO'),
    ('FR COSTA'),
    ('GAUCHO IMOVEIS'),
    ('GRACE GONCALVES'),
    ('HUMBERTO CANALE'),
    ('HÉLIO HIBAS (HC CONSULTORIA)'),
    ('IMOBARRA (VITAL DIAS)'),
    ('IMOVEL LIVRE'),
    ('IMOVELUM PLATAFORMA IMOBILIARIA LTDA'),
    ('I9 INOVE'),
    ('JIUSTI IMOVEIS CONDOMINIOS'),
    ('JOAO MARCO BESSA'),
    ('JOAO MARTINS'),
    ('JSJ'),
    ('VERITAS IMOVEIS SOLUÇÕES'),
    ('LAGORIO'),
    ('LIBERTY ADM (722805)'),
    ('LIVE IMOVEIS'),
    ('LÍDER RIO'),
    ('LOURENCO'),
    ('LUIS ROMEIRO'),
    ('LUIZ FLAVIO'),
    ('LUMAR'),
    ('M V R'),
    ('MAPA'),
    ('MARREIROS IMOVEIS'),
    ('MATERDRADE'),
    ('MAX BROKERS'),
    ('METHODUS'),
    ('MONTE ALEGRE EMPREENDIMENTOS'),
    ('MONTE ALEGRE GESTÃO'),
    ('MONTENEGRO'),
    ('MORAES E VECCHI'),
    ('NELIO GOMES'),
    ('OBJETIVA'),
    ('OKRE'),
    ('PAULO SAMPAIO'),
    ('PINTAS IMOVEIS'),
    ('R N P FORMOSO CORRETAGEM'),
    ('SPECIAL RESIDENCE'),
    ('R&SA GESTÃO'),
    ('RCJ (ROGERIO CASSIANO)'),
    ('RDJ'),
    ('REAL UP'),
    ('RHIAN AZEREDO'),
    ('RIBAS HP'),
    ('RJ VILLELA'),
    ('RODRIGO ARRUDA'),
    ('R SOARES'),
    ('SCASTTRO IMOVEIS'),
    ('SELLING'),
    ('SELMA MARIA CARDOSO'),
    ('SM ADM'),
    ('SPIN'),
    ('SUA CASA DIGITAL'),
    ('TAGS IMOVEIS'),
    ('TRATTO IMOVEIS'),
    ('TRAVASSOS'),
    ('SERRA REAL'),
    ('TWP'),
    ('VÂNIA AMARAL'),
    ('VENDABLE'),
    ('VIVIAN MANSUR'),
    ('MTT 100'),
    ('MTT 300'),
    ('MTT 500'),
    ('MTT 600'),
    ('ADAK'),
    ('NATELMA'),
    ('PAULA ADRIANA'),
    ('RAFAEL PENNA'),
    ('TDC'),
    ('VALVERDE E FERNANDES'),
    ('BSJ'),
    ('MICHELE FREITAS'),
    ('ACVM'),
    ('SILVÉRIO IMÓVEIS'),
    ('ANDREIA BAFFA'),
    ('IMOPRET'),
    ('LIBERTY ADM (614835)'),
    ('WALKER')
)
select coalesce(i.nome, fe.nome_provisorio) as nome_atual, fe.cnpj_o2
from faturas_esperadas fe
left join imobiliarias i on i.id = fe.imobiliaria_id
where fe.seguradora = 'TOKIO' and fe.ativo = true
  and not exists (
    select 1 from esperado e
    where upper(trim(coalesce(i.nome, fe.nome_provisorio))) = upper(trim(e.parceiro))
       or upper(coalesce(i.nome, fe.nome_provisorio)) like '%' || upper(trim(e.parceiro)) || '%'
       or upper(trim(e.parceiro)) like '%' || upper(coalesce(i.nome, fe.nome_provisorio)) || '%'
  )
order by nome_atual;
