create table if not exists public.integracao_formularios_log (
  id bigint generated by default as identity primary key,
  origem text not null,
  resposta_id text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null,
  bitrix_entity_type_id integer,
  bitrix_item_id bigint,
  erro text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (origem, resposta_id)
);

alter table public.integracao_formularios_log enable row level security;

-- A tabela é utilizada somente pelas APIs de servidor com service role.
-- Nenhuma política pública é criada intencionalmente.
